### ISSUE TITLE
Function of onConfirm does not return a log

### ISSUE THREAD

**Issue by JheysaMaria** [aldabil21/react-scheduler#100]
This ticket is referenced to ticket #89 so sorry for the late response to that.

Below is my code. I tried adding or updating an existing event however the console.log in the second line does not trigger which I think means that handleConfirm itself does not trigger.
[handleConfirm issue.txt](https://github.com/aldabil21/react-scheduler/files/10257599/handleConfirm.issue.txt)

**Comment by aldabil21** [comment]
Hi

I tried your code, and the `console.log` runs eveny time in add/edit.

![Screenshot 2022-12-19 at 12 06 21 PM](https://user-images.githubusercontent.com/58398437/208388971-0fb06034-bdba-495a-ba99-4660c76ab4ff.png)

To take this forward, can you please try to replicate this issue in a sandbox I can look into?

Perhaps start from forking this sandbox: https://codesandbox.io/s/remote-data-j13ei

**Comment by aldabil21** [comment]
Hmm, I'm curious to see what surrounding your Scheduler component.
Can you try to add up your code into the sandbox step by step, until you be able to replicate it?
