### ISSUE TITLE
Custom event field names

### ISSUE THREAD

**Issue by JheysaMaria** [aldabil21/react-scheduler#101]
I can see that it only renders if the event is in this format: 
`
{
    event_id: 1,
    title: "Event 1",
    start: new Date(new Date(new Date().setHours(9)).setMinutes(0)),
    end: new Date(new Date(new Date().setHours(10)).setMinutes(0)),
}
`

is there a way I can view events on different format like this one?

`
{
    event_id: 1,
    event_name: "Event 1",
    event_start_date: new Date(new Date(new Date().setHours(9)).setMinutes(0)),
    event_end_date: new Date(new Date(new Date().setHours(10)).setMinutes(0)),
}
`

**Comment by aldabil21** [comment]
4 key fields are mandatory 
- event_id
- title
- start
- end

This is not an issue for you, map your events array and return the right keys.
