### ISSUE TITLE
Error with nextjs  ,  Module not found: Can't resolve '@emotion/react'

### ISSUE THREAD

**Issue by M4rkWhite** [aldabil21/react-scheduler#104]
Module not found: Can't resolve '@emotion/react'

**Comment by mcrisostomo** [comment]
I have the same error. But my situation is in React.

There's some modules that could not be found and looking in the develolper's example, i found some libraries in his package.json that is not mentioned in documentation.

Just run:
`npm install @aldabil/react-scheduler @emotion/react @emotion/styled @mui/icons-material @mui/material @mui/x-date-pickers date-fns`

or:
`yarn add @aldabil/react-scheduler @emotion/react @emotion/styled @mui/icons-material @mui/material @mui/x-date-pickers date-fns`

I believe that it will help you

**Comment by mcrisostomo** [comment]
@aldabil21 could you update your install script?

**Comment by aldabil21** [comment]
@mcrisostomo `Mui` is listed in the _peerDependencies_, which also requires `emotion`.

Unless if you are using `styled-components`, in this case this scheduler component wont be suitable anyway, cuz why would you have 2 styling engines as deps?

how would you suggest addressing this?

**Comment by mcrisostomo** [comment]
Hi @aldabil21, i've seen that is listed as peerDependencies in your package.json file. But if we aren't install these other dependencies, we are facing problems like this as told by @M4rkWhite and me. What if you move these to the main dependencies? Maybe it will help us.
