### ISSUE TITLE
Custom event modal

### ISSUE THREAD

**Issue by naor10** [aldabil21/react-scheduler#112]
Hi,

Thanks for this awesome package.

Is it possible to make the event modal more customizable?

It would be very helpful if I could add custom components fields in it.

**Comment by aldabil21** [comment]
Hi
You can put up your own modal from scratch. use `customEditor` prop, ans see this example https://codesandbox.io/s/customeditor-tt2pf

is that what you looking for?

**Comment by naor10** [comment]
Indeed.
I'll check this.
Thanks!
