### ISSUE TITLE
Screen Size Responsive

### ISSUE THREAD

**Issue by JheysaMaria** [aldabil21/react-scheduler#122]
Just want to ask in considering the responsiveness of the modal on different screens?

Is there a way I can modify the CSS of the modal? Considering that this is not the only modal I am using.

Here's a picture:
![image](https://user-images.githubusercontent.com/72681996/210739130-228922ba-d8a3-4557-bf00-f01439c92c39.png)

**Comment by aldabil21** [comment]
You can use `customEditor` and render your own form and fields with full control.
here is a simple example: https://codesandbox.io/s/customeditor-tt2pf

re-open if you still have issues
