### ISSUE TITLE
All day event is shown only on month view

### ISSUE THREAD

**Issue by naor10** [aldabil21/react-scheduler#129]
Hi,

If I have a full day event such as:
{
    event_id: 1,
    title: "Event 1",
    start: new Date("2023-01-15T00:00:00.000Z"),
    end: new Date("2023-01-15T00:00:00.000Z"),
    disabled: true,
    admin_id: [1, 2, 3, 4]
  },

The event is shown only on month view, but not on week/day view.

**Comment by aldabil21** [comment]
Hi

Month view does not care about "hour", so it will bee visible.

Week view cares about hour, and since start/end time is the same, it will have a height of 0px. So won't be visible.

Can you let me know why you would want to render an event with identical start/end time?

**Comment by naor10** [comment]
Currently this is how we store a full day event at the DB.

**Comment by aldabil21** [comment]
In this case, you can `map` your `events` array, and do something like
```js
//...
allDay: isEqual(event.start, event.end) 
//...
```
Does that solve your issue?

**Comment by naor10** [comment]
Great thanks!
