### ISSUE TITLE
Unable to getCurrent Day / Week / Month

### ISSUE THREAD

**Issue by Janushan** [aldabil21/react-scheduler#13]
Awesome repo btw
Love what you're doing

When I was trying out the repo I could not find a way to extract the current day / week / month and see the changes as the user switches between different days / weeks / months / years.

Is this possible?

This sort of feature would be helpful to for an API query so the server and filter events between a start and end date

**Comment by aldabil21** [comment]
Hi @Janushan 

I'm not sure if this might be specific to your needs.
For now there is the `remoteEvents` prop that will give you the date range depends on user navigation.
it's like :
```
<Scheduler 
//...
remoteEvents:{query=>{
 // query have date start - end depend on the current view
}}
//...
/>
```

Check out this [sandbox](https://codesandbox.io/s/remote-data-j13ei) to see it in action.

let me know if that helps

**Comment by Janushan** [comment]
that's perfect!
thank you!

**Comment by Janushan** [comment]
I've pushed a commit to potentially update the documentation since I missed the query.
Feel free to merge if you feel it might be helpful to others.

Will now close this issue.
Thanks again!

**Comment by aldabil21** [comment]
Glad it helped.
Thank you, appreciated!
