### ISSUE TITLE
React error at onDelete function

### ISSUE THREAD

**Issue by naor10** [aldabil21/react-scheduler#135]
Hi,

When deleting an event by using `onDelete` function, a react error message appears on the console:
"Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function."

It can be seen here:
https://codesandbox.io/s/remote-data-j13ei

Thank you for this great package.

**Comment by aldabil21** [comment]
Thank you for reporting. 
This was fixed before, I will take a look asap

**Comment by aldabil21** [comment]
Fixed in `2.6.10`
