### ISSUE TITLE
Events with the same time are displayed on top each other 

### ISSUE THREAD

**Issue by naor10** [aldabil21/react-scheduler#140]
Hi,

Please look at the attached images.
Events with the same time are displayed on top each other in day/week view.

Can you improve this display like showing the events side by side?

Many thanks.

![image](https://user-images.githubusercontent.com/41241989/220601507-4d2fcc75-e1e5-4e88-96f4-dceb6ddd5a25.png)

![image](https://user-images.githubusercontent.com/41241989/220601559-c644d89a-e50c-4ce5-923e-620a061f81eb.png)

**Comment by aldabil21** [comment]
for sure, this could be better.

**Comment by naor10** [comment]
Hi man,
Do you have an estimation when this enhancement will be done?

**Comment by naonn** [comment]
Hello
Can you fix this bug - each new event is falling on the previous event - making it impossible to see previous events.[
![image001](https://user-images.githubusercontent.com/128289011/227778394-3b7fff55-97f2-4887-ae09-4ea4cc90e99f.png)
](url)

**Comment by aldabil21** [comment]
Hey folks.
Apologize, I was not available recently.
Check out the latet version, which has an approach pretty much close to Google Calendar.
Feel free to re-open if it still has issues.

**Comment by naor10** [comment]
Thank you, it looks much better now.
But now I get a bunch of errors in the console.

In addition, when clicking on the date picker, the calendar crashes.

![image](https://user-images.githubusercontent.com/41241989/227855699-31bf86f5-081f-450e-bf93-6d7ae6f9d284.png)

**Comment by aldabil21** [comment]
Yeah, since version `2.7.0` this Scheduler needs a `x-date` pickers version `>= 6`
I assume you still have version 5?

**Comment by naor10** [comment]
Indeed, Thanks!
