### ISSUE TITLE
Is there a quarter view mode like 90 days view and on calender date cell to add some string like eg: sun as day1

### ISSUE THREAD

**Issue by BansodeSahithiDeshmukh** [aldabil21/react-scheduler#141]
Hello @aldabil21,

trying to have quarter view mode and add string on week [0,1,2,3,4,5] cells as sun as day 1. is there a way to implement this.

Thanks

**Comment by aldabil21** [comment]
Hi

- Quarter mode will need to be added, no option for it yet.
- You can use `weekStartOn` to choose which day the week starts on.

**Comment by BansodeSahithiDeshmukh** [comment]
Thankyou!!
weekStartOn i have used to see the week starts, can we extra string text into the cell?

Eg: in week view horizontally 18 Mon is visible in a cell can i add a string in the cell like "day1"?

**Comment by aldabil21** [comment]
Hmm, this should be easy to implement, there is a `cellRenderer` concept for body cells, but not header cells.
I will put that in my list of todos.
If you feel fancy, PRs are welcome.
