### ISSUE TITLE
Add setFields in useScheduler hook

### ISSUE THREAD

**Issue by TianhongZhang** [aldabil21/react-scheduler#143]
We use the fields prop in Scheduler component to custom the event editor, and we need a way to update some fields such as changing the options for a Select custom field. Currently, fields can't be changed even if we put the value in a state variable of the parent component. Is it possible to add the setFields function in the useScheduler hook similar to setEvents and setTimeZone?

Short of that, any suggestion on how to update fields after the Scheduler has been created?

Thanks

**Comment by aldabil21** [comment]
Currently, if you want a full controll of the editor/fields, it might be better to override the editor and write your own fields, state. Example sandbox: https://codesandbox.io/s/customeditor-tt2pf

**Comment by TianhongZhang** [comment]
Thanks for your quick response. I will give it try in the custom editor. Great library!

**Comment by aldabil21** [comment]
Feel free to re-open if you have any issues
