### ISSUE TITLE
Is it possible to add checks onConfirm on the backend?

### ISSUE THREAD

**Issue by dylanpjx** [aldabil21/react-scheduler#144]
Given that onConfirm expects a promise of the created event, how do I add checks on the backend and discard any unwanted events.

eg. Each user should only be able to book 2 hours per week
-> User books a 3 hour slot 
-> Discard event
-> What should the backend return onConfirm such that the event does not render on the board?

**Comment by aldabil21** [comment]
Of course, this is your own backend logic, the Scheduler component doesn't need to know about.

You can use the `onConfirm` & `onDelete` props to sync the Scheduler component with your backend

**Comment by dylanpjx** [comment]
Sorry, I edited my post earlier, wrote the wrong method name for onConfirm.

I have read the "remote data" example arleady, but I'm not sure what I should return to `handleConfirm` if I want to discard the created event.

**Comment by aldabil21** [comment]
Throw an error, reject a promise, or return a falsy value like unrefined. 

Let me know if it didn't work

**Comment by dylanpjx** [comment]
I threw an error from my backend and the Scheduler stops rendering, ie. the page is empty, until the page is refreshed.

**Comment by dylanpjx** [comment]
I managed to "hack" the method by returning `{...event, start: null, end: null }` in my `catch(err)` block. The Scheduler works as intended that way.

**Comment by aldabil21** [comment]
This should not be the case, it should work by thrown error.
I will get back once I'm able to test it.

**Comment by aldabil21** [comment]
I've updated the sanbox example to make it fails in some cases.
You have to return a promise the resolve/reject. Returning success with a wrong event obj will cause a failure, and that's the normal behaviour.

Take a look the example: https://codesandbox.io/s/remote-data-j13ei


Feel free to re-open if you still have issues
