### ISSUE TITLE
Is there a way to make the scheduler render after state change?

### ISSUE THREAD

**Issue by kacpermordka** [aldabil21/react-scheduler#148]
Hello,

really great job with that lib!

I have a question.. 
i'm fetching array of events using axios from, api and then using useState hook to set up state from response. 
Why, when i pass data from state to parameter 'events' - the component is not rerendering?
How can i deal with it?

The data from api is not exacly with same field names as event should have, is there a way to map them?

thans for reply in advance.

**Comment by aldabil21** [comment]
Hi, 

Yes once the scheduler is mounted it will not rerender, this also related to #147 , I'm still looking at it.

But in your case, if you just want to update the `events` prop, you can use the `useScheduler` hook, it has a `setEvents` methods to update the events internally.

Try that and let me if it works for you

**Comment by kacpermordka** [comment]
Hello again,

useScheduler hook is enough for me, thanks for help!

**Comment by kacpermordka** [comment]
Hey there,

in version 2.7.3 the way of forced rerender has changed, before i was using useScheduler hook.
Now i should use calendarRef ?
do You have any working example witch data fetch and next rerender ? i'm not sure how should i use this new feature :)

**Comment by aldabil21** [comment]
I guess you been using `setEvents` from the previous `useScheduler`.
You can do the same and much more with `calendarRef`.

If before you had:
```
const { setEvents } = useScheduler();

// .... use `setEvents([/*Updated Events*/])` method somewhere
```

Now you can do:
```
 const calendarRef = useRef<SchedulerRef>(null);

// .... use `calendarRef.current.scheduler.handleState([/*Updated Events*/], "events")` method somewhere

return <Scheduler
      ref={calendarRef}
      //...
  />

```
