### ISSUE TITLE
export data

### ISSUE THREAD

**Issue by BansodeSahithiDeshmukh** [aldabil21/react-scheduler#149]
Hello @aldabil21,

Is there any built export data functionality? where the scheduler details being exported to the excel.

Thanks in Advance for the response.

**Comment by aldabil21** [comment]
Hi

The scheduler cannot assume which data you want to export, it only know that an event must have 4 fields, which are: `event_id`, `title`, `start`, and `end`.

If you want to export data, you already have the `events` data in hand, so you can make an export functionality out side of the `Scheduler` component. This is an example sandbox for exporting data as CSV that might deliver tha idea: https://codesandbox.io/s/csv-generate-0swvcd?file=/src/App.js
