### ISSUE TITLE
Module not found: Can't resolve '@mui/icons-material/ArrowLeftRounded'

### ISSUE THREAD

**Issue by Juggi84** [aldabil21/react-scheduler#15]
Hi @aldabil21,

I was trying to install your scheduler, but unfortunately my system can't compile it after the install. The error message is: 
Module not found: Can't resolve '@mui/icons-material/ArrowLeftRounded' in '..\node_modules\@aldabil\react-scheduler\dist'

Could you help me please.

Thank you so much!
Best Jochen

**Comment by aldabil21** [comment]
Hi @Juggi84 

try install `@mui/icons-material`.
`@mui/material` & `@mui/icons-material` & `@mui/lab` all are peer dependencies. This component won't work unless you have them.

Probably I should've state this in the Readme, if you are not __already__ using mui/icons/lab/date-fns/emotion in you projects, then perhaps this component might be suitable for the project.

Let me know if this helps
