### ISSUE TITLE
Customize Event Popper

### ISSUE THREAD

**Issue by tuchris** [aldabil21/react-scheduler#150]
Hi and thanks for the great work.

I wonder if it would be possible to fully customize the Event Popper (the view that appears if you click on an event).
At the moment, the only option is to add content via ViewerExtraComponent.

Concretely, I would like to have an additional button next to edit and delete.

Thanks in advance and BR
Chris

**Comment by aldabil21** [comment]
Hi

Unfortunately this is not possible with the current setup.
Hopefully will do make it possible in future releases.
