### ISSUE TITLE
set week,month,day props error 

### ISSUE THREAD

**Issue by ricksxj** [aldabil21/react-scheduler#162]
set week,month,day props error from 2.6.14

**Comment by aldabil21** [comment]
Can you elaborate?

**Comment by ricksxj** [comment]
set these props works in 2.6.13 but not work in new release version.
![屏幕截图 2023-03-23 105615](https://user-images.githubusercontent.com/3755498/227088970-3ee02bcf-f848-46ed-8a39-8b494aa3e431.png)

![2023-03-23 105841](https://user-images.githubusercontent.com/3755498/227089382-b09b2a70-8926-4f83-a537-f58c181c3cae.png)

**Comment by aldabil21** [comment]
If you define custom `week`/`month`/`day` props, you will have to add all the __required__ props.
Click on the prop to see type definition
