### ISSUE TITLE
empty space at the bottom of the event box

### ISSUE THREAD

**Issue by HoWRiM** [aldabil21/react-scheduler#165]
<img width="617" alt="스크린샷 2023-03-23 오후 2 25 24" src="https://user-images.githubusercontent.com/25731456/227111882-b5907001-0a29-4ed3-8a24-c548cac32288.png">

Hi
Is there no way to fill the empty space at the bottom of the event box?
What can be inferred seems to be lacking as much as the number of border lines in the middle.

Have a good day.

**Comment by HoWRiM** [comment]
answer yourself.
It's a css issue.
If you have the same problem, check out box-sizing.

**Comment by aldabil21** [comment]
Hi

This is not a CSS issue. if you force override `boxSizing` you will have the empty space in the top section.
Its a `height` calculation issue. I will work on it.

Apologize for the delay, I was not available in the past several days

**Comment by aldabil21** [comment]
Please checkout the latest version.
Feel free to re-open if it still has issues.

**Comment by HoWRiM** [comment]
perfect!
