### ISSUE TITLE
Changing the colour of the dates?

### ISSUE THREAD

**Issue by luke-buttifant** [aldabil21/react-scheduler#17]
Is it possible to change the colours of the text? I think this would be a good feature to add, as the calender is not very visible on a dark background. As you can see below:

![image](https://user-images.githubusercontent.com/64266031/159361445-87572844-7a92-4b7d-bca6-eb952a15f275.png)
![image](https://user-images.githubusercontent.com/64266031/159361371-670d345f-cf1f-45a9-a524-2003cbded0ef.png)

**Comment by aldabil21** [comment]
hmm... also, why the default blue & purple colors? are those your primary/secondary theme setup? seems not.
Cuz those colors should come from your theme primary/secondary colors.

I will take a look and get back to you, haven't made an investigation with a dark theme actually... opss

**Comment by aldabil21** [comment]
I took a look at it, theming works correctlly as intended.
Perhaps you did override the Typography color in your theme setup to force it to be always black? Check your Mui theme setup.


![light](https://user-images.githubusercontent.com/58398437/159417390-66c3df16-f92d-4931-96a7-6ff1ee2a33a4.JPG)

![dark](https://user-images.githubusercontent.com/58398437/159417418-a5c9892d-55ab-46e5-b748-adce552169c8.JPG)
