### ISSUE TITLE
Overwriting styles

### ISSUE THREAD

**Issue by juandrepanther** [aldabil21/react-scheduler#172]
Hi and thanks for this scheduler. Just wanted to know is that possible to overwrite its styles? Maybe adding classNames to each MUI element will be good enough? In my project I am using MUI and theme file, but I wanna to independently change styles for scheduler only.

Thanks and looking forward from you!

**Comment by aldabil21** [comment]
Hi. Which element exactly?
For the event, you can you use `cellRenderer` to entirely override its style.
For the viewer/popper, you can use `customViewer` to entirely override its style.
and for the editor, you can totally override it with `customEditor`

Is there anything else I missed?
