### ISSUE TITLE
facing issue on confirm

### ISSUE THREAD

**Issue by BansodeSahithiDeshmukh** [aldabil21/react-scheduler#173]
Hello @aldabil21,

I have put all my issues in the code sandbox here is the link:  https://codesandbox.io/s/friendly-wilbur-8y2m0l?file=/src/App.tsx.

Issue1:  I have created a customEditor where on click of confirm event is not binding.
Issue 2:  I'm using a eventRenderer where on an event will have a icon and on click a menu to be shown, but my eventRenderer is not working as expected.
Issue 3: as I'm using a custom editor on click of any scheduler my  custom editor is getting poped up, but im not able pass feilds to custom editor.  Basically i need the resource of that click event in my custom editor.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/123079502/228852874-e2e9dbf6-c4ef-4bf5-8aa3-05db69491cc4.png">

above image related to issue 3: where purple mark I have clicked on my custom editor I want to see the resource of it i;e John, I'm trying to pass fields to editor but couldn't.

Thanks in Advance!! @aldabil21 

could u please help me to figure out with the issues.

**Comment by aldabil21** [comment]
1. If you are using resources, where is the assignee/admin_id? you missed that. add the `admin_id` to the event object, otherwise it will not show.
2. `eventRenderer` added in v2.5.1, but you are using an old version 1.0.38. I guess because you still use Mui v4?
3. If you are using `customEditor`, then the `fields` prop is useless and will not be used. Just add the select input in your custom editor.

Here are the changes: https://codesandbox.io/s/falling-pond-rngx5q?file=/src/App.tsx

**Comment by aldabil21** [comment]
I guess you used the `fields` prop to pass the `admin_id` on click empty cell. You were actually right. The sandbox above have this solved as well

Does this solves all your issues?

**Comment by aldabil21** [comment]
With the version you are using, there is no way to override the event element in order to add your custom icon.

Can you upgrade?

**Comment by BansodeSahithiDeshmukh** [comment]
I have "@aldabil/react-scheduler": "^2.6.13" and @mui "@mui/icons-material": "^5.11.11",
    "@mui/material": "^5.11.7" versions. is this an issue? @aldabil21

**Comment by BansodeSahithiDeshmukh** [comment]
Thankyou!! I had took an approach and all my issues have been solved!!

@aldabil21  Thankyou !! you have saved and this library is awesome!!

**Comment by aldabil21** [comment]
With this version you have `eventrenderer` prop available. Glad you figured it out

**Comment by aldabil21** [comment]
Hi, I have gave it a try, there are some limitations.
I've made some improvments in v2.7.6 if you might wanna upgrade.
here is the updated example: https://codesandbox.io/s/falling-pond-rngx5q

**Comment by BansodeSahithiDeshmukh** [comment]
@aldabil21  Thankyou!! for the response and code sandbox. will have a look.
