### ISSUE TITLE
renderDeps property

### ISSUE THREAD

**Issue by seemix** [aldabil21/react-scheduler#174]
In older version there was a renderDeps which I used to re-render Scheduler component when data in redux state changes. How can I do it in newer versions? Thank you)

**Comment by aldabil21** [comment]
Hi

There is no more `useScheduler`.
You can use `ref` to programmatically update internal state with `ref.scheduler.handleState` method. I believe this approach is safer than the old `renderDeps`

**Comment by seemix** [comment]
Thank you for quick reply, I'll try to use it
