### ISSUE TITLE
Missing navigation events

### ISSUE THREAD

**Issue by thomasouvre** [aldabil21/react-scheduler#180]
Hi, 

Can we add some navigation events like `onSelectedDateChange`, `onViewChange` and when user clic on next/back in navigation header ?
These events could be very usefull when we need to synchronize the rest of the UI according to the state of the scheduler.

Thanks by advance

**Comment by aldabil21** [comment]
These events can be added. I will add them as soon as possible.

Meanwhile, if you would like to have a full controll over the navigation, you can disable it with `navigation={false}` & `disableViewNavigator` props, and add your own custom solution, using the `ref` can help update internal state.

**Comment by thomasouvre** [comment]
Thanks for the tips, I can do that. Can you add a class to target the div with all the navigation UI ? If I want to replace it with my own I need to apply a display none on it. Or just skip rendering this div when the `navigation` props value is false ?

**Comment by aldabil21** [comment]
It skips rendering the nav elements, but the wrapper stays, which might be an issue.
I've added some changes to totally skip the navigation if disabled.
also, added `onSelectedDateChange` & `onViewChange` events if you still want to use default navigation.
