### ISSUE TITLE
Bug with custom event renderer

### ISSUE THREAD

**Issue by seemix** [aldabil21/react-scheduler#182]
If I use code like this:
```
 eventRenderer={({ event }) => {
            return (<div>{event.start.toLocaleTimeString('ru-RU', { timeStyle: 'short' })}</div>);
        }}
```
When I click to event the viewerExtraComponent doesn't appear, also drag-n-drop doesn't work. The problem resolves if event renderer is standard.

**Comment by aldabil21** [comment]
yes thats correct, you have to pass other props to your element, I guess the ReadMe needs update. It should be like

```
eventRenderer: (props: EventRendererProps): React.ReactNode
```

Check the `EventRendererProps` https://github.com/aldabil21/react-scheduler/blob/5a641fd4dfc8224c1c58f31eb1da99d8ae1c56a8/src/lib/types.ts#L82

Using you example you can do:

```
eventRenderer={({ event, ...props }) => {
            return (<div {...props}>{event.start.toLocaleTimeString('ru-RU', { timeStyle: 'short' })}</div>);
        }}
```
