### ISSUE TITLE
TypeError: renderInput is not a function while creating/updating an event.

### ISSUE THREAD

**Issue by aaqibrasool** [aldabil21/react-scheduler#183]
Hi,

I'm using the scheduler package in a NextJs application and everything was working fine until I tried creating or editing an event by clicking on a time slot or the edit button on an event. Unfortunately, I'm encountering the following error:

**Unhandled Runtime Error
TypeError: renderInput is not a function**

I suspect the issue is in the "event creation pop-up". I've tried looking for a solution in previously closed issues, but couldn't find anything relevant.

Can someone please help me resolve this issue? Any assistance would be greatly appreciated.

Thanks!

**Comment by aldabil21** [comment]
Hi

I could not replicate the issue, can you replicate it any codesandbox?

This error seems to be  you are using a version >= `2.7.0`,  but you still has `@mui/x-date-pickers` version 5.
version >= `2.7.0` requires `@mui/x-date-pickers` version 6

**Comment by aaqibrasool** [comment]
I am happy to report that the issue has been resolved by updating to the latest version of **@mui-x-pickers.** I had already been using version 5 of @mui/x-date-pickers in my application. After installing the latest version of **@mui-x-pickers**, the issue was fixed. I want to thank you for your help in resolving this issue.
