### ISSUE TITLE
Events not updating on change/fetch

### ISSUE THREAD

**Issue by jordanshardy** [aldabil21/react-scheduler#184]
Updating the array on `events` doesn't trigger a re-render. If the array has elements on initial render, the events show on the Schedular (no matter the view day, week, month)

However, if the array is updated after the initial render, the changes are not triggering a re-render and thus the events are not displaying on the Scheduler in any of the views.

See this loom link for video showing the issue: https://www.loom.com/share/76b0f24d3c294b29ab0cadec41f83d33

**Comment by aldabil21** [comment]
This is intentional.
you can use the `ref` to update the events programatically.
See: https://github.com/aldabil21/react-scheduler#schedulerref
