### ISSUE TITLE
Resources as rows and time as columns

### ISSUE THREAD

**Issue by PuscasSebi** [aldabil21/react-scheduler#185]
is there a way to show those different as title suggest ? 
<img width="1434" alt="Screenshot 2023-04-12 at 19 50 36" src="https://user-images.githubusercontent.com/5778685/231527666-8b84ee3b-26d3-4e8d-a5d6-f4f39e62bb83.png">

**Comment by aldabil21** [comment]
currently, this option is not available.

However, you can use the `resourceViewMode="tabs"` option to make it looks better.
