### ISSUE TITLE
Error on event click

### ISSUE THREAD

**Issue by HoWRiM** [aldabil21/react-scheduler#187]
The viewer should appear, but I get an error.
I really don't know. 😭
Any guesses? 
I share my dependency list.

![스크린샷 2023-04-14 오전 12 41 56](https://user-images.githubusercontent.com/25731456/231814854-ba902c69-65f1-4511-8658-61426c0787d3.png)

![스크린샷 2023-04-14 오전 12 44 33](https://user-images.githubusercontent.com/25731456/231814880-d2de0dd6-eec9-49eb-bb1e-e19baa726449.png)

![스크린샷 2023-04-14 오전 12 51 25](https://user-images.githubusercontent.com/25731456/231815504-4f99d4cd-500f-486f-ba9a-39e8f8bea967.png)

**Comment by aldabil21** [comment]
I believe you are using the `translations` prop, but you are not passing all the translation strings.
There is a `form.delete` field that is missing.
See: https://github.com/aldabil21/react-scheduler/blob/5a641fd4dfc8224c1c58f31eb1da99d8ae1c56a8/src/lib/types.ts#L61

Let me know if you still have issue

**Comment by HoWRiM** [comment]
It's perfectly resolved.
Thank you!
