### ISSUE TITLE
Datepicker issue

### ISSUE THREAD

**Issue by BansodeSahithiDeshmukh** [aldabil21/react-scheduler#188]
![image](https://user-images.githubusercontent.com/123079502/231996643-351e7769-ddce-47e2-9296-f3e761ca7294.png)

when i click on the date picker icon the date selection is not populating on the screen.  @aldabil21  can you please suggest on the issue.

**Comment by BansodeSahithiDeshmukh** [comment]
Here are my package and scheduler declaration.
![image](https://user-images.githubusercontent.com/123079502/231998144-ffcc57cb-cea8-4804-8f9c-704b2a2c6cd8.png)

![image](https://user-images.githubusercontent.com/123079502/231998762-60326bab-5f47-4fcd-8ede-a8ae062a16e7.png)


and one more issue is my file is .tsx file and when i use scheduler props in it, it shows below error shown in image. what i have to do?
![image](https://user-images.githubusercontent.com/123079502/231999535-3c0e9e0b-a383-4f83-bf70-45086e561ed6.png)

**Comment by aldabil21** [comment]
1. This seems to be a custom date picker, to populate the selected date use `ref` helper method `handleState`, see https://github.com/aldabil21/react-scheduler#schedulerref

2. This is a type error, you also has errors in the `month`/`week`/`day` props. you are not providing the expected data type. your element might be `undefined` which is not accepted. Make sure you return the correct types.

**Comment by BansodeSahithiDeshmukh** [comment]
@aldabil21 Thanks for the suggestion, But in my code im not using any custom datepicker its the same date picker comming up using the @aldabil21/react-scheduler library. I have just added the css looks.
