### ISSUE TITLE
@aldabil21 Thanks for the suggestion, But in my code I'm not using any custom date picker its the same date picker populated up using the @aldabil21/react-scheduler library. I have just added the css looks. issue facing is when I click the calendar icon im unable to see the dates card to select the date

### ISSUE THREAD

**Issue by BansodeSahithiDeshmukh** [aldabil21/react-scheduler#191]
@aldabil21 Thanks for the suggestion, But in my code I'm not using any custom date picker its the same date picker populated up using the @aldabil21/react-scheduler library. I have just added the css looks. issue facing is when I click the calendar icon im unable to see the dates card to select the date

_Originally posted by @BansodeSahithiDeshmukh in https://github.com/aldabil21/react-scheduler/issues/188#issuecomment-1511349448_

**Comment by aldabil21** [comment]
There is no "calendar icon" in the calendar navigator. I'm not sure what's your issue.

Please re-open if you have a code sandbox to represent the issue

**Comment by BansodeSahithiDeshmukh** [comment]
Hello @aldabil21, sorry for the delay of code sandbox, what i have observed is this issue is in the 2.6.13 version, here i have provided the codesanbox link : https://codesandbox.io/s/compassionate-night-7sim74?file=/src/App.tsx where on click of icon unable to see the datepicker.

where to test when i have upgraded the version, there datepicker visibilty and declaration on view is different i;e https://codesandbox.io/s/falling-pond-rngx5q

Thanks in advance.
