### ISSUE TITLE
Column layout for Day view 

### ISSUE THREAD

**Issue by karlsonru** [aldabil21/react-scheduler#193]
Hello, thank you for your lib! 

Here is a small suggestion: 
Would it be possible to place all events in one column one after another in Day view? Maybe add flex layout like an optional prop? 

Day view looks good on desktop, but on mobile screens it's a little bit overheaded. Time column isn't always necessary. 
And placing one event in the morning and another one in the evening - makes you scroll from top to bottom. 
Increasing time step in Day view doesn't help in this situation as well. Still looks strange due to different sizes of events with a different duration. 
 
Seems that placing them in [Stack](https://mui.com/material-ui/react-stack/) component could be a solution. Maybe another way to do same with a Grid (not familiar with it).

**Comment by aldabil21** [comment]
Hi

I guess you want an `agenda` view, I will try to add that asap

**Comment by karlsonru** [comment]
> Hi
> 
> I guess you want an `agenda` view, I will try to add that asap

Would be great, thank you!

**Comment by karlsonru** [comment]
@aldabil21 Thank you very much. That's great.
