### ISSUE TITLE
UseScheduler() issue in 2.7.6 version

### ISSUE THREAD

**Issue by BansodeSahithiDeshmukh** [aldabil21/react-scheduler#195]
![image](https://user-images.githubusercontent.com/123079502/235122986-49b03313-a6cd-47a9-a905-44d47a9a27e6.png)
initially i was using 2.6.13 version when I upgraded it to 2.7.6 then I'm getting below error.
![image](https://user-images.githubusercontent.com/123079502/235123327-68a2ddbf-ba5e-45ac-947c-740d549df550.png)

I'm using useScheduler to update my events, resources in my code and i have imported it as well below is the code.
![image](https://user-images.githubusercontent.com/123079502/235123625-681654ed-07ff-4555-9997-a5027eb19c4a.png)
![image](https://user-images.githubusercontent.com/123079502/235123796-c88b6384-daff-4c93-a934-53174ad77f5a.png)
![image](https://user-images.githubusercontent.com/123079502/235123973-39823f92-08a6-4d92-abad-fa9e22238e83.png)

Thanks in advance!!

**Comment by aldabil21** [comment]
Hi

Since 2.7.3 there is no more `useScheduler`. You can easily replace that with `schedulerRef`.

Please check the ReadMe https://github.com/aldabil21/react-scheduler#schedulerref

In your code example, you can do

```
calendarRef.current.scheduler.handleState("schedulerContextobj.events", "events");
calendarRef.current.scheduler.handleState("schedulerContextobj.selectedDate", "selectedDate");
// ... You get the rest...
``
