### ISSUE TITLE
Is it possible to move time on X axis(TOP) in view="day"

### ISSUE THREAD

**Issue by furyOO7** [aldabil21/react-scheduler#196]

**Comment by aldabil21** [comment]
Unfortunately, not possible.
It will be hard to manage time horizontally, it may go too wide.
Is there a good case for this? Can you point me to any known calendars/scheduler which does that? So I can see an actual reference of what you mean

**Comment by boreens** [comment]
https://github.com/namespace-ee/react-calendar-timeline
https://codepen.io/mariusandra/pen/ONrQaX
It would be awesome to combine it together with resources
