### ISSUE TITLE
Starting position of event renderer

### ISSUE THREAD

**Issue by onejae** [aldabil21/react-scheduler#197]
![image](https://user-images.githubusercontent.com/8242504/235170673-63051fa2-afe2-42dc-a776-39f2f511b61a.png)

Hi, 
Thanks for your works, really amazing component. 

I found something, not sure it was designed as it is or not

The start position of the event display box does not match the grid in the calendar
This gap gets worse as it goes down

**Comment by aldabil21** [comment]
Hi

I've seen similar issue before #165, do you have any CSS that force changing the `box-sizing` property? 

To eleminate if it's a CSS issue, can you check this sandbox does it have the same issue? https://codesandbox.io/s/heights-test-y9ct17
If no, can you add your code to make it breaks like this? This will help me debug

Thank you

**Comment by onejae** [comment]
Thank you for very quick response!

The same issue happens on the link you provided.

Actually the first screen capture I posted was also from sandbox examples, not my code.

This issue happens on Firefox, chrome. I haven't checked edge. 

Thanks in advance!

**Comment by ralcant** [comment]
I tried the link and it works as expected. I was having the same error, and it was indeed a matter of `box-sizing`. By using Chakra UI it places `box-sizing: border-box` to almost everything. I fixed it by wrapping the Scheduler on a div like:
```javascript
<div class="scheduler-container">
   <Scheduler
   ...
   />
</div>
```
and in the css

```css
.scheduler-container * {
  box-sizing: initial !important
}
```
