### ISSUE TITLE
Cannot disable the user from "adding events"

### ISSUE THREAD

**Issue by AdamKyle** [aldabil21/react-scheduler#198]
I can get around this by creating a custom view for it and say this action is not allowed, but this should be an option in the api that isn't listed and I havent checked the types to see if there is an option.

I can, through your api, disable drag and drop, the ability to edit an event, delete an event and so on. How ever you can, as the person who's allowed to view, but not do anything, add an event still.

## Proposal

add an option that allows me disable the ability to add an event, that is:

If false, clicking on the calendar does not bring up the modal to add an event.

If true, clicking on the calendar does bring up the modal to add an event.

Thoughts?

**Comment by aldabil21** [comment]
Hi

This option is offered in a cell-based solution, using `cellRenderer` and optionally `onEventDrop`.
Since this sometimes is requested to be enable only on a selection of cells.

Check the [example sandbox](https://codesandbox.io/s/custom-cell-action-n02dv), does it solve your problem?

**Comment by AdamKyle** [comment]
that does help, yes, thank you.
