### ISSUE TITLE
How to set Scheduler readonly?

### ISSUE THREAD

**Issue by MikentGuo** [aldabil21/react-scheduler#20]
Can I set Scheduler readonly?
In the readony mode the users can't  add/delete/change the event.

**Comment by aldabil21** [comment]
Hi
Unfortunately, this has not been made internally.
If you want to limit/restrict the add/edit/delete, you would have to override the `cellRenderer`/`customEditor`/`onDelete` to stop the default behaviour, and make it like a readonly calendar. the Edit/Delete icon buttons would still be visible though, right now there is no way to remove them by option/props.

**Comment by MikentGuo** [comment]
Hi
Got it. Thanks anyway.
