### ISSUE TITLE
Include full day when going every 30 minutes

### ISSUE THREAD

**Issue by ralcant** [aldabil21/react-scheduler#200]
Thank you for such an awesome package!

Is there a way to render cells every 30 minutes and include the full day (from 00:00 to 23:59), I have tried to do

```javascript
<Scheduler
   week={{
        startHour: 0,
        endHour: 23,
        step: 30,
    }}
}
/>
```
but that shows from 00:00 to 11:30pm (given endHour is 23 so it only gets until 23:30). `endHour` doesn't seem to be able to be a float so things like `23.5` don't work sadly.

**Comment by aldabil21** [comment]
Good point

I will look into it

**Comment by aldabil21** [comment]
After #203 it will work out of the box, just need to change `endHour` to 24

**Comment by ralcant** [comment]
I tried and see a bit of a margin for exact events and ones that end at midnight. Any suggestion on why this might be happening / how to fix it?


![image](https://github.com/aldabil21/react-scheduler/assets/44732064/0d01eb54-eb15-4b4b-a1df-644cb0b47f2c)
![image](https://github.com/aldabil21/react-scheduler/assets/44732064/21147521-e02a-4779-89ac-fec6434380dd)
