### ISSUE TITLE
Error while changing Calendar by using month picker and date picker.

### ISSUE THREAD

**Issue by admiral44** [aldabil21/react-scheduler#205]
Dear support team,

I am encountering an error when trying to change the month or date directly using the left top side month and date picker in the "Editor/Viewer Override" page of our Demos. The error occurs when I make the selection, and it is impacting the functionality of the page.

To reproduce the issue, please follow these steps:

1. Go to the Demos section.
2. Open the "Editor/Viewer Override" page by visiting the URL: "https://codesandbox.io/s/customeditor-tt2pf".
3. Try to change the month or date using the left top side month and date picker.

You will notice that an error is thrown, preventing the smooth transition or update of the selected month or date.

I kindly request your assistance in resolving this issue. Please let me know if you require any additional information or clarification.

Thank you for your prompt attention to this matter.

Best regards,
Shubham

@aldabil21 @jackstenglein @senegoid @npapapietro @sreejithshaji @luizfilho @almax-21 @Janushan @jucopera

**Comment by aldabil21** [comment]
Hi @admiral44 

I think the demo was not updated well, it was running with `@mui` < v5.8.6 [ref](https://github.com/mui/mui-x/blob/c9c6d3793bf3b39826aebe464a44f3c147e0a80c/packages/x-date-pickers/package.json#L58)

I updated the demo to use `v5.8.6`. 

I should update the `peerDependencies` though

**Comment by admiral44** [comment]
Thank you for your prompt response. I appreciate your willingness to address the issue.
Could you please provide more details or clarify the specific aspect that requires fixing?

Thank you for your cooperation. I look forward to your response.

**Comment by aldabil21** [comment]
The `@mui/material` package needs to be >= v5.8.6
Nothing else
Feel free to re-open if you still have issue with the demo link you provided

**Comment by admiral44** [comment]
Hi @aldabil21,

I recently installed your updated package, but I'm still encountering an error. 
Could you please provide me with some guidance or steps to troubleshoot the error? Any help or suggestions would be greatly appreciated.

Thank you in advance for your assistance.
