### ISSUE TITLE
Same issue affecting on my side. even if install your updated package.

### ISSUE THREAD

**Issue by admiral44** [aldabil21/react-scheduler#206]
Hi @aldabil21 

I recently installed your updated package, but I'm still encountering an error.
Could you please provide me with some guidance or steps to troubleshoot the error? Any help or suggestions would be greatly appreciated.

Thank you in advance for your assistance.

**Comment by aldabil21** [comment]
Hi

Can you share a reproduction sandbox?

**Comment by admiral44** [comment]
Hi, 

Sorry I don't have production sandbox, but if I share you my package.json file screen shot will this work .?

**Comment by aldabil21** [comment]
here is the basic example: https://codesandbox.io/s/react-scheduler-demo-standard-v96bd
you can copy your `<Scheduler ... ` component inside it

**Comment by admiral44** [comment]
![image](https://github.com/aldabil21/react-scheduler/assets/36560341/65566efa-2b15-4b98-97c9-9b0877700709)

**Comment by aldabil21** [comment]
Upgrade `@mui/material` to v5.8.6 or above
