### ISSUE TITLE
Getting issue while creating Events.

### ISSUE THREAD

**Issue by admiral44** [aldabil21/react-scheduler#207]
Hi @aldabil21,

Hope your doing well. Sorry to bother you once again. 
I got issue while creating event.

I used your old demo link which you shared with me. Here : https://codesandbox.io/s/react-scheduler-demo-standard-v96bd

I used same packages which you are using in that demo.

I share some screen shots in which you got all details like **package.json** file.
Scheduler component and error and one more thing thanks you now [ Month and Date picker is working ].

1. Package.json File.

Apart from Data-picker npm package, I'm using lots of different packages like day.js, moment.js and @mui/x-date-pickers-pro
are those file are affecting this error?

![Json](https://github.com/aldabil21/react-scheduler/assets/36560341/1bdcbee2-ea0d-4c7c-b921-d66681c506a9)

----------------------------------------------------------------------------------------------------------------------------------

2.  If you click on any block of Scheduler to create an event it will throw error.

![Schduler](https://github.com/aldabil21/react-scheduler/assets/36560341/3d8623d9-c836-478e-9203-e2aaa94e1f14)

----------------------------------------------------------------------------------------------------------------------------------
3.  In console I'm getting this error. below both Images.

![Error_create_Event](https://github.com/aldabil21/react-scheduler/assets/36560341/1286a6fa-58f3-4f16-91c9-305b409486ef)

----------------------------------------------------------------------------------------------------------------------------------

![Error-2](https://github.com/aldabil21/react-scheduler/assets/36560341/170e990e-c1c4-4612-a964-d8abaee6be61)

----------------------------------------------------------------------------------------------------------------------------------
please guide me on this issue. Watting for your response.

**Comment by aldabil21** [comment]
Hi

The demo link seems to work fine.
I can't tell if there is a conflict with other libs you are using, you would have to try to replicate a sample in a sandbox so I can be able to look into it.

If you could make a small sandbox with the libs you are using, I would be able to provide better help

Feel free to re-open once you can provide that
