### ISSUE TITLE
Bug: top value miscalculation in grid

### ISSUE THREAD

**Issue by Trevodorax** [aldabil21/react-scheduler#208]
I am encountering a problem with the display of events in the grid.
When an event is created in the first rows, everything is fine.
But the lowest they are in the rows, the more a little offset is added, so the events get displayed a bit too low.

Here is a screenshot of what that looks like for me :
<img width="1248" alt="Screenshot 2023-07-04 at 23 57 13" src="https://github.com/aldabil21/react-scheduler/assets/73560235/11a6ceae-1025-439c-af70-cfc0ea32258d">

I can provide the code if it helps, but I also get the issue with the codesandbox demo in the docs, so I don't think the problem is my code.

**Comment by aldabil21** [comment]
Hi

Some of the demos has `v2.7.8` which has this bug, its been fixed after. I updated all demos to use `v2.7.10` which has this issue solved

Thx for reporting

**Comment by Trevodorax** [comment]
> Hi
> 
> Some of the demos has `v2.7.8` which has this bug, its been fixed after. I updated all demos to use `v2.7.10` which has this issue solved
> 
> Thx for reporting

In my project I use 2.7.10 and it's still doing the bug, any idea how to fix it ?

**Comment by aldabil21** [comment]
This is most likely a css conflict of `box-sizing`.
do you have a rule of focrcing `box-sizing: border-box`?
are you using the @Mui `CssBaseline`, it will solve that?.

**Comment by Trevodorax** [comment]
> This is most likely a css conflict of `box-sizing`.
> 
> do you have a rule of focrcing `box-sizing: border-box`?
> 
> are you using the @Mui `CssBaseline`, it will solve that.

Oh no, I don't use MUI in the rest of my project...
What would be the minimal config for it to work properly ?

**Comment by aldabil21** [comment]
you can give the scheduler a classname, then target the child grid with a `box-sizing: content-box`

**Comment by Trevodorax** [comment]
Works like a charm thanks you !
For anyone encountering similar issues, here is what I did:

JSX:
```jsx
<div className={styles.schedule}>
  <Scheduler {...schedulerProps} />
</div>
```

SCSS:
```scss
.schedule {
    * {
      box-sizing: content-box;
    }
  }
```

Thanks again for your fast answers aldabil !

**Comment by paulobordignon** [comment]
.rs__cell {
  box-sizing: content-box;
}

this CSS above worked better for me.
