### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by papsavas** [aldabil21/react-scheduler#214]
I've spent alot of time trying to access prop types through `ComponentProps` for some customizations.

**Im suggesting exporting every possible type under index, for better UX**

Also, currently event data type (`ProcessedEvent`) is extending `CalendarEvents` with a loose Record (`Record<string, any>`).

Would be helpful if 
- `CalendarEvents` was exported
- Generics would be used instead of a loose Record to gain inference on additional data fields

**Comment by aldabil21** [comment]
Agree

I will try to make sometime for this asap. If you also have the capacity to PR it would be great

**Comment by joaquincardosorios** [comment]
I'm having problems using locale, I'm trying to setting any other locale (es, es-CL, es-GB...etc) but I'm having errors
