### ISSUE TITLE
Height of rows

### ISSUE THREAD

**Issue by MacMah0n** [aldabil21/react-scheduler#215]
Hello !

It is possible to change the 60px height of hour cells ? 
I would like to reduce the global height of the table.

Thanks

**Comment by aldabil21** [comment]
The minimum 60 is decided by the vertical time-cell in mobile view. a value lower than 60 will most likely cause the hour/time-cell to break line and will overlap.

So I don't think I can make the minimum height less than that, However, feel free to re-open if you have a suggestion that can solve this issue.
