### ISSUE TITLE
Missing translations for field error messages

### ISSUE THREAD

**Issue by bohrsty** [aldabil21/react-scheduler#217]
I was looking for a simple to use scheduler, based on (or usable with) react and material-ui and found this as a very good match (hoping that recurrence is on a high position of the agenda :smile: ), thank you for your work...

As I'm and my users are German, translation is one of the key features. Generally it works fine with the `translations`-prop, but if verification of fields (default and custom) fails, the error messages are still in English (understandable as they weren't mentioned in the prop). Is there a way to translate those error messages in the current version, or is this feature missing?

**Comment by aldabil21** [comment]
Agree, the `translations` should include the validation messages, I guess we missed that.

Another option that you can implement right now without delay, is to use `customEditor` , you can define your own form, inputs, validations etc... Check the customEditor demo in the ReadMe

**Comment by bohrsty** [comment]
Thank you so far, I'll take a deeper look on the demo and check if its worth it, or if my users and me can wait for an updated version...

**Comment by aldabil21** [comment]
v2.7.14 have  `translations.validation` object

**Comment by bohrsty** [comment]
It works like a charm... thank you very much!
