### ISSUE TITLE
Handle state changes  in external components

### ISSUE THREAD

**Issue by Juliaxddd** [aldabil21/react-scheduler#219]
Hey, what is the correct way to manipulate active month (in month view) via external button? Below i paste my broken tryies   

```
const calendarRef = useRef<SchedulerRef>(null);
    <>  
<Button onClick={() => {
              calendarRef.current?.scheduler.handleGotoDay(
                new Date(
                  dayjs(calendarRef.current?.scheduler?.selectedDate).subtract(
                    1,
                    "month"
                  )
                )
              );
          }}>next day</Button>
          
          actual month is ${????}
          </>
```

**Comment by aldabil21** [comment]
If I understood you correctly, you want to manage the month externally.
You can handle that with external state.
is this example helpful? https://codesandbox.io/s/219-lzxvyx

**Comment by aldabil21** [comment]
When having 100's of events, the render could be costly. controlling state internally was applied.
