### ISSUE TITLE
Is there an option to create an event which lasts for multiple days and is not marked as allDay?

### ISSUE THREAD

**Issue by DavydMelnychenko** [aldabil21/react-scheduler#221]
Hi, I really like your scheduler and decided to use it in my pet project. Great job! However, I'm facing an issue when trying to create events that last for multiple days.

Whenever I attempt to create an event that spans more than one day, it automatically marks it as an all-day event and displays it at the top of the scheduler, even when I explicitly set 'allDay' to false. Is there any way to avoid this behavior?

As a temporary workaround, I've created a function that splits the date at midnight. For example, if the input is `'26.07.2023 20:00'` and `'28.07.2023 15:00'`, the function returns `[{start: 26.07.2023 20:00, end: 26.07.2023 23:59}, {start: 27.07.2023 00:00, end: 27.07.2023 23:59}, {start: 28.07.2023 00:00, end: 28.07.2023 15:00}]`. This way, I can create three events with the same ID. However, I wonder if there's a better approach to handle this situation.

I create event like this:
```
//event is element of eventList
let timePassed = separateDateOnMidnight(event.start, event.end);
  timePassed.map(timePassedDay => {
    events.push({
      event_id: event.id,
      user_id: event.userId,
      title: event.title,
      type: event.type,
      start: new Date(timePassedDay.start),
      end: new Date(timePassedDay.end),
      description: event.description || "",
      allDay: false
    });
});
```

**Comment by aldabil21** [comment]
Hi
This design is intentional, the top space is meant for "multi-day" events and "allDay" events. This is kinda inspired by Google calendar.

I guess you would like something like the "month" view, which is not the case with week/day view


I'm not sure I can plan making this possible, so forgive me will close this as not planned
