### ISSUE TITLE
translations.validation prop is not respected by custom fields

### ISSUE THREAD

**Issue by bohrsty** [aldabil21/react-scheduler#225]
Hello again, after the fix of validation translation in #217, I found out, that `translations.validation` entries are not used in custom editor fields you add with `fields` prop (tested only with select).

**Comment by aldabil21** [comment]
Did you upgrade to `v2.7.15`?

Here is a sandbox to demostrate, https://codesandbox.io/s/225-yz2tlq?file=/src/App.js

Feel free to re-open if it sill has issues

**Comment by bohrsty** [comment]
Yes I did upgrade to v2.7.15, but it isn't working either in your sandbox (please look at the screenshot):

![screenshot](https://github.com/aldabil21/react-scheduler/assets/2415071/6ce74d58-c491-45be-9f0d-7983716902d9)

Maybe I wasn't clear enough: I did not selected any option, I just opened (touched) the field and then clicked outside twice to blur it...

I would re-open it, but I think I haven't the permission, I can't find a button to re-open...
