### ISSUE TITLE
Question: Recurring events

### ISSUE THREAD

**Issue by PodaruDragos** [aldabil21/react-scheduler#23]
Hey, great library.

I was just curious about when recurring events will be implemented, since I saw you have it on the todo list.
This is just a question, not a demand or anything like that.

**Comment by aldabil21** [comment]
Hi @PodaruDragos 
This would be nice to implement, perhaps cuz I didnt yet reach a point of really needing it in my work, so I always allocate the time for other work that have higher priority. So I really can't say when I would do it. I'm so sorry. And I welcome any PRs for improvments.
