### ISSUE TITLE
Custom select field options not updated after loading from api finished

### ISSUE THREAD

**Issue by bohrsty** [aldabil21/react-scheduler#231]
I've another question (or problem) regarding the custom select fields: my options are loaded via http rest api, but after the loading finished, the options aren't updated, the select stays empty. When I put the array directly in the options key, they're shown, if I delay the loading (like in the example below), nothing is shown.

```jsx
const [options, setOptions] = useState([]);
useEffect(() => {
    setTimeout(() => {
        setOptions([
            {id: 1, value: 1, text: 'Example 1'},
            {id: 2, value: 2, text: 'Example 2'},
        ]);
    }, 1000);
},[]);

return(
    <Scheduler
        view={'month'}
        events{[]}
        fields={[
            {
                name: 'field1',
                type: 'select',
                config: {
                    label: 'Field 1',
                },
                options: options,
            }
        ]}
    />
);
```

The first question is, is it currently possible to load the options delayed (the `loading` key/prop indicates "yes")?

If "yes", is the way in the example the correct one?

Thanks for your support...

**Comment by aldabil21** [comment]
The internal state will not be updated in this approach.
Once your async code get executed, you can use the `SchedulerRef` to update the internal state `fields`. You can see some info on the ReadMe about the methods of the ref (or see the types).

I'm on my phone now can't provide a sandbox, I can do that later on

**Comment by bohrsty** [comment]
Ok. that's an interesting way... :smile: 

I've found a way to get it working, but I think I don't understand the concept fully. Do I have to update the whole `fields` array every time one of my custom fields options were loaded async, like this?

```jsx
const [field1, setField1] = useState([]);
const [field2, setField2] = useState([]);
const schedulerRef = useRef(null);

// load options for first field
useEffect(() => {
    setTimeout(() => {
        setField1([
            {id: 1, value: 1, text: 'Field 1 Example 1'},
            {id: 2, value: 2, text: 'Field 1 Example 2'},
        ]);
    }, 1000);
},[]);
// load options for second field
useEffect(() => {
    setTimeout(() => {
        setField2([
            {id: 1, value: 1, text: 'Field 2 Example 1'},
            {id: 2, value: 2, text: 'Field 2 Example 2'},
        ]);
    }, 1500);
},[]);

useEffect(() => {
    schedulerRef.current.scheduler.handleState([
        {
            name: 'field1',
            type: 'select',
            config: {
                label: 'Field 1',
            },
            options: field1,
        },
        {
            name: 'field2',
            type: 'select',
            config: {
                label: 'Field 2',
            },
            options: field2,
        },
    ]);
}, [field1, field2]);

return(
    <Scheduler
        ref={schedulerRef}
        view={'month'}
        events{[]}
    />
);
```

Of cause I would check which options state has changed, but do I always have to update the whole `fields` state?

Maybe you could provide an example how to do this correctly, if you've got time, at the moment I have a way of getting my options loaded async... thanks so far...

**Comment by aldabil21** [comment]
I think you dont need the useState/useEffect here at all.
After your http call just map the fields and update the one you need.

To make this short, you have 2 ways:
- use the ref to update internal state
- use your custom form and make your own setup
