### ISSUE TITLE
Some issue with UI 

### ISSUE THREAD

**Issue by trung1704ptit** [aldabil21/react-scheduler#234]
Hi,

I am getting one issue with this lib, when I add some items but see one issue below.
the items are not in line with the row. items moved down a little.
I am using Next.js 13, react 18.2, typescript.
![image](https://github.com/aldabil21/react-scheduler/assets/54926746/3488d6b6-da22-455d-8873-f26d79b3c227)

**Comment by aldabil21** [comment]
Check #208 
if you believe its not the same issue, feel free to reopen with example sandbox of repro
