### ISSUE TITLE
Functions not rerendering on change

### ISSUE THREAD

**Issue by Sideways-Sky** [aldabil21/react-scheduler#235]
Preface: I may be completely ignorant and/or wrong, let me know ;)

### The Problem
As of right now, almost all functions passed as props do not rerender when they are changed on runtime. 
I believe this is what makes it impossible to read any updated value from a react state in these said prop functions.

### Possible Fix
I pecked through your code and it looks like in your store provider you use a useEffect to update onEventDrop and customEditor. 

src/lib/store/provider.tsx 
lines 13 - 25:
```
export const StoreProvider = ({ children, initial }: Props) => {
  const [state, set] = useState<Store>({ ...initialStore, ...defaultProps(initial) });

  useEffect(() => {
    set((prev) => ({
      ...prev,
      onEventDrop: initial.onEventDrop,
      customEditor: initial.customEditor,
    }));
    // Rerender if changed on some props
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initial.onEventDrop, initial.customEditor]);

```
I'm the dev but perhaps it'd be as simple as adding the dependencies and updating them in the hook.

### My Implementation
Here's an example of what I'm trying to do: (Hopefully this will provide some context)
![code](https://github.com/aldabil21/react-scheduler/assets/96632645/f7368224-8732-4520-92fa-6cfc506a39ef)
Please let me know if I'm entirely in the wrong and missed a crucial detail!
Thanks!

**Comment by aldabil21** [comment]
I'm not quite sure what the issue is here, define your meaning by saying "dosent rerender".
The `getRemoteEvent` meant be fired when you navigate,  meaning: when the `RemoteQuery` changes (the from/to date range).

Limiting the deps is intentional, if you want to update some internal state, use the `SchedulerRef`

However, if you would like to elaborate more about the your issue, please provide copiable example or a sandbox example. Image screenshot is not helpful here

**Comment by Sideways-Sky** [comment]
My apologies, let me see if I can explain it better.

You can view what I am talking about here:
[Codesandbox](https://codesandbox.io/p/sandbox/boring-almeida-s8854w?file=%2Fcomponents%2Fschedule%2Findex.tsx%3A61%2C66)
in `components/schedule/index.tsx`

Try entering an event, then navigating to another date, then back to where you entered.
You'd expect the date to be there, but it's not.

The `RemoteQuery` is accurate. 
The `events` state (the `IEvent` one) has the event. 
The `getEvents` callback is rerendered with the updated state. 
The `getRemoteEvents` is **not** rerendered. Hence its internal cache of the `events` state is not updated. Thereby not displaying any events.

I suppose what I mean when a function rerenders is that it is updated with the state that it calls upon.

I've tried using a hook to update it using the `SchedulerRef` but it doesn't seem to set it.

This also happens to most of the functions. Not allowing them to read any external state.

Hopefully, that explained it. If not, please let me know.
Thanks!

**Comment by aldabil21** [comment]
Hi
Thanks for the example, it made it easier to understand.

First, I was not able to run your sandbox, but, the issue you trying to say is clear, and I made a simple repro here: https://codesandbox.io/s/235-kgg673?file=/src/scheduler.js

With the setup you working with, you actually have no "remote" events, The `getRemoteEvents` will work as intended if you fetch the events somewhere "remote", then displaying them, in this case it will work as inteded.

However, your setup is just saving the `event` locally, so I believe you don't actually need the `getRemoteEvents`, just use the `events` prop instead, and the state will be sync.

See the example sandbox I above, if you use `getRemoteEvents`, it will be as you described, but, comment out `getRemoteEvents` and use `events` instead. It will work as intended.

Hope this helps, elaborate if thats not what you meant.

**Comment by aldabil21** [comment]
To make this clear

The `getRemoteEvents` function meant to be used with server-side **"remote"** fetching events. Which means your `onConfirm` should be saving the event server-side, and once you navigate back and forth with dates, it will fetch the correct events with the date-range.

However, in your case, you are only saving them in a `useState`, you do not need the `getRemoteEvents` to return the local `state`, use the `events` prop directly.

Feel free to re-open if you still believe this is an issue
