### ISSUE TITLE
UI issue, Items moved down alittle

### ISSUE THREAD

**Issue by trung1704ptit** [aldabil21/react-scheduler#236]
Hi,
I got an issue with this lib when trying to render some booking time.
the items seem to move down a little when the time exceeds to larger number
example start at 8 AM then okay fine, if start at 17h then the item moved down compare with the row.

![image](https://github.com/aldabil21/react-scheduler/assets/54926746/31b3629a-6e38-4030-a81a-535ba0b36404)

**Comment by aldabil21** [comment]
Have you checked #208? 
Most likely you have a setup to force override the CSS of the grid.
Please fork this sandbox https://codesandbox.io/s/react-scheduler-demo-standard-v96bd and try replicate your case, otherwise I can't provide a better help

**Comment by trung1704ptit** [comment]
@aldabil21  thanks, I read the comments, and add small CSS
.rs__cell {
  box-sizing: content-box;
}

it will be fixed.
