### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by seemix** [aldabil21/react-scheduler#243]
Hello. How can I call custom editor modal by clicking on event (except extra viewer window). Thanks

**Comment by aldabil21** [comment]
Check `customEditor` Prop.
There is example in the ReadMe

**Comment by seemix** [comment]
Sure it works. Maybe my question is dumb but how can I show custom editor by just clicking on event? When I click on it I firstly see this popup  [https://ibb.co/9q4MJDx](url) To get to my custom editor I must click on edit button. Thanks for your patience)

**Comment by aldabil21** [comment]
Oh yeh, apologize didn't get it first.

you can use `eventRenderer` to render your own element, and you can use something like `onClick={openEditModal}`

In `openEditModal`, either you use the `SchedulerRef` to open the internal editor, or make your own editor.

Hope this make sense

**Comment by seemix** [comment]
Thank you for the feedback. Really your suggestion makes sense. But the problem which I faced now is: by clicking on my custom rendered element I got the props.event object like this: ` { event_id , start, end, admin_id, color }`. But when I'm clicking on empty field to add new record I got the scheduler object: `{
state: state obj, 
close(): void
loading(status: boolean): void
edited?: ProcessedEvent
onConfirm(event: ProcessedEvent, action:EventActions): void
}`

So what is the best way to use the same modal component for editing items and for adding new ones? Can you suggest me something? Thanks

**Comment by aldabil21** [comment]
> But when I'm clicking on empty field to add new record

This is unrelated to `eventRenderer`, this is a `cell` action not `event` action.

To overriding cell click you can use your own `cellRenderer`.

Maybe I misunderstood, if you provide a sample sandbox I may give a better help

**Comment by seemix** [comment]
Oh, thanks. Using the cellRenderer option solved my issue.
