### ISSUE TITLE
Event becomes undraggable after using eventRenderer

### ISSUE THREAD

**Issue by avet-davtyan** [aldabil21/react-scheduler#244]
---
title: "Undraggable Behavior with eventRenderer in Latest Version"
---

### Issue Description

In previous versions, like 2.5.13, the following code snippet with an `eventRenderer` function worked perfectly:

```jsx
eventRenderer={(event) => {
  return <div>{event.title}</div>;
}}
```
I'm aware that it must be {event} in newer versions

**Comment by aldabil21** [comment]
Please upgeade to [2.6.7](https://github.com/aldabil21/react-scheduler/releases/tag/2.7.6)

You will use it like: 

```js
eventRenderer={({event, ...props}) => {
  return <div {...props}>{event.title}</div>;
}}
```

**Comment by avet-davtyan** [comment]
The code above works fine for month view, but it doesn't work for the week view, can you please check it out?

https://codesandbox.io/embed/custom-event-renderer-forked-hmr69j?fontsize=14&hidenavigation=1&theme=dark

**Comment by avet-davtyan** [comment]
okay got it thanks
