### ISSUE TITLE
Events not getting updated

### ISSUE THREAD

**Issue by Korangamanish4** [aldabil21/react-scheduler#245]
Updating the events is not getting reflected in the calender unless I reload the page and send those events again .

**Comment by aldabil21** [comment]
If you shared an example portion of your code, perhaps I will give a better help.

Are you using local state with onConfirm? or remote fetch? or not either one of them? I can't guess whats your issue.

Here is an example that might get you started: https://codesandbox.io/s/245-v8jnl2?file=/src/App.js

Feel free to open if you still have issues, and include minimal code example of your setup

**Comment by Korangamanish4** [comment]
``@aldabil21  Here is the code,

I called an API that returns me my events, I am saving those events in a state and passing that state to Events property of library. Events are not visible in Calender unless I refresh the page.

const [events, setEvents] = useState([])

<Scheduler
              className="custom-schedular"
              view="week"
              week={{
                weekDays: [0, 1, 2, 3, 4, 5, 6],
                weekStartOn: 1,
                startHour: 0,
                endHour: 23,
                step: 60,
              }}
              day={{
                startHour: 0,
                endHour: 23,
                step: 60,
              }}
              events={Events ? Events : []}
              viewerExtraComponent={(fields, event) =>
                extraComponent(fields, event)
              }
            />
