### ISSUE TITLE
Problem wirt locale

### ISSUE THREAD

**Issue by joaquincardosorios** [aldabil21/react-scheduler#248]
I'm having problems using locale, I'm trying to setting any other locale (es, es-CL, es-GB...etc) but I'm having errors

![image](https://github.com/aldabil21/react-scheduler/assets/105686879/b3e8f3fd-61e2-4d61-805d-4b8c471a1936)

**Comment by aldabil21** [comment]
Hi

locale is not a `string` 
its the locale object from `date-fns`
see: https://date-fns.org/v2.30.0/docs/I18n

Example:
```jsx

import { enGB, eo, ru } from 'date-fns/locale'

// ...
<Scheduler
 locale={enGB}
...//

/>
 

```
