### ISSUE TITLE
Add prop to disable event editor

### ISSUE THREAD

**Issue by jackstenglein** [aldabil21/react-scheduler#250]
In some cases, I want the scheduler to function as a read-only calendar. In this case, I have to provide a custom editor which immediately closes itself in a useEffect hook. However, this leads to a poor UX where the user clicks on an empty time slot, and the screen darkens for a second while the custom editor is first displayed and then brightens again after it has closed itself.

It would be nice if the scheduler could receive a prop like `disableNewEvents` or `disableEventEditor` that would prevent the editor from opening at all. Note that passing `editable={false}` doesn't currently do this (maybe it's intended to?)

**Comment by aldabil21** [comment]
`editable` prop are meant to be for `events` only.
The `useEffect` hack is not recommened.
To override the **cell action** (which opens the editor by default), you would use the `cellRenderer` prop for each view, and render your own "button" or "div", that will do nothing (or do something else other than open editor).

Example of custom cell action: https://codesandbox.io/s/custom-cell-action-n02dv

However, it seems that its good idea to make the root prop `editable` also include the **cell action** as well.
will keep this open to rethink it
