### ISSUE TITLE
Invisible events in week view

### ISSUE THREAD

**Issue by naor10** [aldabil21/react-scheduler#254]
Hi,

The week view does not display all events when I have a multi-day event.

Under the purple event, we can see a cropped yellow event and there are more events that are not visible.

Thanks!

![image](https://github.com/aldabil21/react-scheduler/assets/41241989/0a3e7a65-89fb-4bb0-8bcf-dedf1d80fe69)

**Comment by aldabil21** [comment]
Noted

This should be fixed in next release 

Feel free to reopen if it sill has issues

**Comment by naor10** [comment]
Looks better, but still one event is missing (a purple one).

![image (4)](https://github.com/aldabil21/react-scheduler/assets/41241989/e26a5590-510e-4fa0-aa89-3209c2236aa6)
![image (2)](https://github.com/aldabil21/react-scheduler/assets/41241989/cfbd5ed5-3d7e-4bbc-b85c-c5e732426201)

**Comment by aldabil21** [comment]
Hmm

Can you copy your events array here to try it? Remove all fields, just keep the `start` and `end` dates

**Comment by naor10** [comment]
Sure, thanks!
```
{
  "events": [
    {
      "startDate": "2023-09-26T00:00:00.000Z",
      "endDate": "2023-09-26T00:00:00.000Z",
    },
    {
      "startDate": "2023-09-27T00:00:00.000Z",
      "endDate": "2023-09-27T00:00:00.000Z",
    },
    {
      "startDate": "2023-09-24T00:00:00.000Z",
      "endDate": "2023-09-24T00:00:00.000Z",
    },
    {
      "startDate": "2023-09-29T00:00:00.000Z",
      "endDate": "2023-09-29T00:00:00.000Z",
    },
    {
      "startDate": "2023-09-24T09:30:00.000Z",
      "endDate": "2023-09-24T16:00:00.000Z",
    },
    {
      "startDate": "2023-09-24T09:00:00.000Z",
      "endDate": "2023-09-24T16:00:00.000Z",
    },
    {
      "startDate": "2023-09-24T08:00:00.000Z",
      "endDate": "2023-09-28T16:30:00.000Z",
    },
    {
      "startDate": "2023-09-26T08:00:00.000Z",
      "endDate": "2023-09-26T16:30:00.000Z",
    },
    {
      "startDate": "2023-09-26T08:00:00.000Z",
      "endDate": "2023-09-26T16:30:00.000Z",
    },
    {
      "startDate": "2023-09-26T08:00:00.000Z",
      "endDate": "2023-09-26T16:30:00.000Z",
    }
  ]
}
```

**Comment by aldabil21** [comment]
In this list, there is only 1 event that is > 1 day.
I guess you have other events that has the `allDay` prop?

I still can't replicate the issue. Please share an example to replicate it here or in a code sandbox

**Comment by naor10** [comment]
Sure.

Please see it here:
https://codesandbox.io/s/react-scheduler-zjzxwn?file=/src/App.js
