### ISSUE TITLE
is Dark Mode supported?

### ISSUE THREAD

**Issue by qryskalyst20** [aldabil21/react-scheduler#255]
Is there any possible way to style this component so that it can adapts to dark mode? It seems that the text is transparent if the date is not today.

lightmode:
![image](https://github.com/aldabil21/react-scheduler/assets/65181897/74694e69-0dc8-4469-b888-67a56e3aa77b)

darkmode:
![image](https://github.com/aldabil21/react-scheduler/assets/65181897/071a9f45-5903-46f8-b87d-07da8509ac04)

**Comment by aldabil21** [comment]
Dark mode comes from your own Mui theme setup https://mui.com/material-ui/customization/dark-mode/
Switching dark mode in you own theme provider will automatically includes the calendar.
