### ISSUE TITLE
Events not getting updated

### ISSUE THREAD

**Issue by mkoranga1** [aldabil21/react-scheduler#258]
I am calling an API that returns me my events, I am saving those events in a state and passing that state to Events property of the library. Events are not visible in Calender unless I refresh the page.

const [events, setEvents] = useState([])

<Scheduler
className="custom-schedular"
view="week"
week={{
weekDays: [0, 1, 2, 3, 4, 5, 6],
weekStartOn: 1,
startHour: 0,
endHour: 23,
step: 60,
}}
day={{
startHour: 0,
endHour: 23,
step: 60,
}}
events={events ? events : []}
viewerExtraComponent={(fields, event) =>
extraComponent(fields, event)
}
/>

**Comment by Fabio070672** [comment]
Hi. You need to import as below
import { Scheduler, useScheduler } from "@aldabil/react-scheduler";
and after you need to create 
    const { setView, setEvents } = useScheduler();
to have access of setEvents, then you will handle your events

**Comment by mkoranga1** [comment]
@Fabio070672 I tried your solution but it's saying useScheduler() is not a function. 
I am using version 2.7.23
I believe it's a hook but I don't see any hook with that name in node modules.

**Comment by aldabil21** [comment]
@mkoranga1 

The hook was replaced with the `ref`
There is an example in the ReadMe, check the SchedulerRef section

**Comment by mkoranga1** [comment]
@aldabil21  looking at that section I am not able to understand how will I update my events using ref.

**Comment by aldabil21** [comment]
Apologize for late replay

Here is an example sandbox using ref https://codesandbox.io/s/258-k773s3

Another solution also will be to use the `getRemoteEvents` prop, it will provide you with a query of the scheduler time-range, which is ideal for fetching from backend with filtering for perofrmance optimization
