### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by AdrianLaRiva** [aldabil21/react-scheduler#26]
Hi Abdulraoof, it's a great plugin i love it. but i have two questions.

1) it is possible define days available in the calendar? example : allow days only between two dates or week.
2) it is possible define view mode by code and hide the options for the user
![Captura de Pantalla 2022-05-24 a la(s) 19 04 35](https://user-images.githubusercontent.com/25966340/170146021-39f89046-2ecf-4032-bddb-5b95be6e7442.png)

Thanks a lot.

Regards.

**Comment by aldabil21** [comment]
Hi @AdrianLaRiva 

1. It's possible in __week/month__ view to choose certain days using the `weekDays` prop, but not in __days__ view, the days view meant to show all days. However if you want to disable certain days, you can use the `cellRenderer` prop to disable certain days. Example [here](https://codesandbox.io/s/custom-cell-action-n02dv).
2. This option is not within the `Scheduler` component, its just an extra added code to show the difference in the sandbox, you can get rid of it, and define your view using the `resourceViewMode` prop.

Hope this helps
