### ISSUE TITLE
onConfirm not trigger action properly while edit and create event.

### ISSUE THREAD

**Issue by pinkishahub-sdn** [aldabil21/react-scheduler#262]
const handleSubmit = (event, action) => {
    console.log(action);
    return new Promise((resolve, reject) => {
      if (action === "create") {
        createAppointment(event, dispatch)
          .then((result) => {
            resolve({
              ...event,
              event_id: event.event_id,
              result,
            });
          })
          .catch((error) => {
            reject(`Create appointment failed: ${error}`);
          });
      } else if(action === "edit"){
        editAppointment(event, dispatch)
          .then((result) => {
            resolve({
              ...event,
              event_id: event.event_id,
              result,
            });
          })
          .catch((error) => {
            reject(`Edit appointment failed: ${error}`);
          });
      }
    });
  };

<Scheduler
          getRemoteEvents={getAllAppointments}
          dialogMaxWidth="sm"
          fields={[
            {
              name: "description",
              type: "input",
              default: "",
              config: { label: "Details", multiline: true, rows: 4 },
            },
          ]}
          onConfirm={handleSubmit}
          onDelete={handleDelete}
          week={{
            weekDays: [0, 1, 2, 3, 4, 5, 6],
            weekStartOn: 6,
            startHour: 0,
            endHour: 24,
            step: 60,
          }}
          day={{
            startHour: 0,
            endHour: 24,
            step: 60,
            navigation: true,
          }}
          onEventDrop={handleDraggable}
        />

**Comment by aldabil21** [comment]
I'm not sure what do you mean by "not trigger action properly"

I copied your example in a sandbox, and seems to be working as expected in create and edit case https://codesandbox.io/s/onconfirm-f8hzmh

double check your `result` has a valid `event_id`, or if your onConfirm actually throws an error
