### ISSUE TITLE
Dynamic resource not showing according to multiselect.

### ISSUE THREAD

**Issue by pinkishahub-sdn** [aldabil21/react-scheduler#266]
import React, { useEffect, useState, useRef } from "react";
import { Scheduler } from "@aldabil/react-scheduler";
import {
  appointmentList,
  createAppointment,
  deleteAppointment,
  editAppointment,
} from "../../services/appointment.service";
import { useDispatch } from "react-redux";
import { Dropdown } from "react-bootstrap";

export const RESOURCES = [
  {
    resource_id: 1,
    title: "John",
    mobile: "555666777",
    avatar: "https://picsum.photos/200/300",
    color: "#ab2d2d",
  },
  {
    resource_id: 2,
    title: "Sarah",
    mobile: "545678354",
    avatar: "https://picsum.photos/200/300",
    color: "#58ab2d",
  },
  {
    resource_id: 3,
    title: "Joseph",
    mobile: "543678433",
    avatar: "https://picsum.photos/200/300",
    color: "#a001a2",
  },
  {
    resource_id: 4,
    title: "Mera",
    mobile: "507487620",
    avatar: "https://picsum.photos/200/300",
    color: "#08c5bd",
  },
];

const AppointmentCalendar = () => {
  const dispatch = useDispatch();
  const [selectedResource, setSelectedResource] = useState("");
  const [resources, setResources] = useState(RESOURCES);
  const [selectedProviders, setSelectedProviders] = useState([]);
  const getAllAppointments = async () => {
    try {
      const appointmentsData = await appointmentList(dispatch);
      const results = [];

      appointmentsData?.map((value) => {
        try {
          // Parse the date strings into Date objects
          const startDate = new Date(value.start);
          const endDate = new Date(value.end);

          results.push({
            event_id: value._id,
            title: value.title,
            start: startDate,
            end: endDate,
            description: value.description,
            resource_id: 1,
            color: "#566D7E",
          });
        } catch (error) {
          console.error("Error parsing date:", error);
        }
      });
      return results;
    } catch (error) {
      console.error("Error fetching appointments:", error);
    }
  };

  const handleSubmit = (event, action) => {
    return new Promise((resolve, reject) => {
      if (action === "create") {

      } else if (action === "edit") {
      
      }
    });
  };

  const handleDelete = (deletedId) => {
  };

  const handleProviderSelect = (resource_id) => {
    if (selectedProviders.includes(resource_id)) {
      // If the provider is already selected, remove it
      setSelectedProviders((prevSelected) =>
        prevSelected.filter((id) => id !== resource_id)
      );
    } else {
      // If the provider is not selected, add it to the selectedProviders array
      setSelectedProviders((prevSelected) => [...prevSelected, resource_id]);
    }
  };

  useEffect(() => {
    // Update the resources based on the selected providers
    const filteredResources = RESOURCES.filter((resource) =>
      selectedProviders.includes(resource.resource_id)
    );
    setResources(filteredResources);
  }, [selectedProviders])
  
  return (
    <div className="dashboard">
      <div className="data-card">
        <div className="right-section">
          <div className="action-bar">
            <div className="right-actions">
              <div className="date-filter">
              <div>
                  <Dropdown>
                    <Dropdown.Toggle
                      as="div"
                      variant="secondary"
                      id="dropdown-basic"
                      style={{ display: "flex", alignItems: "center" }}
                    >
                      <button className="btn btn-xs icon-button">
                        <i
                          className="fa fa-user-md"
                          style={{ fontSize: "20px" }}
                          aria-hidden="true"
                        ></i>
                      </button>
                    </Dropdown.Toggle>
                    <Dropdown.Menu>
                      {RESOURCES?.map((resource) => (
                        <Dropdown.Item
                          key={resource.resource_id}
                          onClick={() =>
                            handleProviderSelect(resource.resource_id)
                          }
                        >
                          <input
                            type="checkbox"
                            checked={selectedProviders.includes(
                              resource.resource_id
                            )}
                            onChange={() => {}}
                          />{" "}
                          {resource.title}
                        </Dropdown.Item>
                      ))}
                    </Dropdown.Menu>
                  </Dropdown>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Scheduler
          getRemoteEvents={getAllAppointments}
          dialogMaxWidth="sm"
          draggable={false}
          resources={resources}
          resourceViewMode="tabs"
          resourceFields={{
            idField: "resource_id",
            textField: "title",
            subTextField: "mobile",
            avatarField: "title",
          }}
          fields={[
            {
              name: "description",
              type: "input",
              default: "",
              config: { label: "Details", multiline: true, rows: 4 },
            },
          ]}
          onConfirm={handleSubmit}
          onDelete={handleDelete}
          week={{
            weekDays: [0, 1, 2, 3, 4, 5, 6],
            weekStartOn: 6,
            startHour: 0,
            endHour: 24,
            step: 60,
          }}
          day={{
            startHour: 0,
            endHour: 24,
            step: 60,
            navigation: true,
          }}
        />
      </div>
    </div>
  );
};

export default AppointmentCalendar;

**Comment by aldabil21** [comment]
Sorry for the delay
I assume you had this working already
if not yet, feel free re-open with a link to Sandbox to check the issue

thx
