### ISSUE TITLE
How to access start and end dates from the navigator without getRemoteEvents

### ISSUE THREAD

**Issue by Ots-S** [aldabil21/react-scheduler#267]
Hi,

I'm using useList from Refine (useList is an extended version of TanStack Query's ) to fetch events from my API.
But i need to use the start and end dates from the Scheduler navigator as filters for my useList.

Since i can't use useList inside the getRemoteEvents function's, is there another way to access the actual start and end dates and then use `calendarRef.current.scheduler.handleState(fetchedEvents, 'events')` to update my events ?
 ?

Thanks for your work

**Comment by aldabil21** [comment]
Hi

on next release, you can do something similar to the following:

```jsx

//.....
const [rang, setRange] = useState({start, end}) // Set your default rang according to your default view
const { data } = useQuery({
    queryKey: ['events', rang],
    queryFn: () => fetchEvents(rang),
   // ....
});

 const onNavigation = async ({start, end}: RemoteQuery) => { 
    setRange({start, end});
  };

return <Scheduler
    events={data.events}
    getRemoteEvents={onNavigation}
 />

```
