### ISSUE TITLE
./node_modules/@aldabil/react-scheduler/dist/Scheduler.js:1:1002 Module not found: Can't resolve 'date-fns'

### ISSUE THREAD

**Issue by simbolmina** [aldabil21/react-scheduler#27]
Hello,

I'm trying to use this component in a nextJS app but I get this error as soon as I import the component into a page, without using it.

`./node_modules/@aldabil/react-scheduler/dist/Scheduler.js:1:1002
Module not found: Can't resolve 'date-fns'

Import trace for requested module:
./components/Today/Today.jsx
./pages/yonetim.js

https://nextjs.org/docs/messages/module-not-found`

  "dependencies": {
    "@aldabil/react-scheduler": "^2.2.1",
    "i": "^0.3.7",
    "next": "12.1.6",
    "react": "18.1.0",
    "react-dom": "18.1.0"
  },

**Comment by aldabil21** [comment]
Hi @simbolmina 

I gotta admit, this component is heavily opinionted on **Mui** and **date-fns**.
If your project is not _already_ using the Mui material, icons, lab and date-fns, then this component might not be suitable.

So you've to install _peer dependencies_.

Cheers

**Comment by simbolmina** [comment]
Oh okay. Since I'm a new developer there are lots of things I don't know. Thanks for the fast reply.

**Comment by aldabil21** [comment]
Glad you made it!
