### ISSUE TITLE
How can I change button style (color, variant) 

### ISSUE THREAD

**Issue by paramate-tawilapakul** [aldabil21/react-scheduler#274]
How can I change button style when add new, edit or delete event
![1700111939730](https://github.com/aldabil21/react-scheduler/assets/25241404/260a1334-9dc1-4c58-be0f-9977277350da)

![1700112012364](https://github.com/aldabil21/react-scheduler/assets/25241404/a858dd1a-0bee-4204-97bf-4f24a7e232ba)

**Comment by aldabil21** [comment]
You can use `customViewer` and write your own from scratch. search for `customViewer` in the ReadMe
