### ISSUE TITLE
Custom height table

### ISSUE THREAD

**Issue by yelmypech** [aldabil21/react-scheduler#275]
How can I set a dynamic height on the table?

Example 
![Screenshot at Dec 01 00-01-20](https://github.com/aldabil21/react-scheduler/assets/60902211/d0b786a4-1d8a-454a-b9be-69dc010b0cf4)

I currently have it like this

![Screenshot at Dec 01 00-03-39](https://github.com/aldabil21/react-scheduler/assets/60902211/d8aaa423-3fe5-4afa-8548-e256655a8572)

**Comment by aldabil21** [comment]
`height` and `step` both can control the height of the calendar, min height possible is 60px. 

if you want to change the height programatically, you can use the `ref` to change the height.

**Comment by yelmypech** [comment]
I want that min height to be less than 60px for row or hour, for all the table to be smaller. Use ref, is possible?

**Comment by aldabil21** [comment]
less than 60px will break the time line and look bad. mentioned here as well https://github.com/aldabil21/react-scheduler/issues/215
