### ISSUE TITLE
Issues with timeZone prop

### ISSUE THREAD

**Issue by jackstenglein** [aldabil21/react-scheduler#276]
The timeZone prop only seems to be applied to certain elements of the scheduler and not others. For example, if I pass a timezone far enough ahead that it should be the next day, the scheduler still uses my local time zone when I click the `Today` navigation button. Similarly, the time indicator bar doesn't go to the next day and instead disappears since it goes off the bottom of the calendar.

Additionally, with a custom editor, the date passed to the custom editor is in the local timezone, which makes it quite difficult to work with, as I have to convert it to the specified time zone and back.

**Comment by jackstenglein** [comment]
Actually, even without a custom editor, using the timezone prop leads to confusing results when creating events

**Comment by aldabil21** [comment]
The bar seems to be working as expected.
The issue I found is: the `cell` dates are local date, and when adding new event, it will jump to the corrosponsing timezone. For example, you add event at 1pm, then after save, it will be saved onto 4pm (assuming the timezone is +3h ahead)

I will dig more into this

**Comment by aldabil21** [comment]
This is more complicated than I expected
Manipulating the events start/end dates with timeZone will conflict with the new added events.
As example, you click on 1PM cell to add event there, then after saving, the event will be moved to another hour based on your selected timeZone. Feels like kinda misleading. If you have a suggestion/idea to solve this, plz share.

Right now, I had refactored the timezone prop to only affects the current time, like, the `today` hightligh & button, and the current time bar.

**Comment by jackstenglein** [comment]
Thanks for looking, but I think the change you made is actually a step in the wrong direction. Previously the events were displayed at the correct time if I passed the timezone, but now they are just always displayed at the local time regardless of the timezone prop.

**Comment by uxbert-fe** [comment]
This is intentional, for the reasons I mentioned above

any suggestions on how you would like to approach this issue? I can adapt and change.

**Comment by jackstenglein** [comment]
I think it would make the most sense if the events still displayed in the selected timezone, but then if the editor also took into account the selected timezone in order to avoid the event jumping to a different time when adding

**Comment by jackstenglein** [comment]
Reopening for PR #356.
