### ISSUE TITLE
Disable drag&drop and editing option

### ISSUE THREAD

**Issue by shoebjoarder** [aldabil21/react-scheduler#28]
Is there any way to disable the drag&drop feature as well as the editing of a schedule?

**Comment by Sitaras** [comment]
Is there any way to disable the drag&drop feature as well as the editing of a schedule?

**Comment by aldabil21** [comment]
```
{
    event_id: 1,
    // ....
    disabled: true, // <-- adding this will do it
}
```

**Comment by Sitaras** [comment]
If I want to disable only the drag&drop ?

**Comment by aldabil21** [comment]
Hmm.
I think question is, why would you?
if there is a certain condition that allow/disallow an event to be moved, then you can override the `onEventDrop` prop, then check for that certain condition, then process and return the event accordingly weither to move it or return it to original place.
