### ISSUE TITLE
Possibility to change the event title

### ISSUE THREAD

**Issue by paulobordignon** [aldabil21/react-scheduler#285]
Today the event title is: Event 1 

![image](https://github.com/aldabil21/react-scheduler/assets/24723164/479ce7ba-c4a1-4368-aad8-00fa184eae54)

The possibility to change this value for a custom field like customer name it will be very useful.

**Comment by aldabil21** [comment]
I think you took this screenshot from the example sandbox, which has random list of events `Event 1` and `Event 2` etc...

of course you would want to supply your own data as list of event with whatevet `title` you want

refer to readme

**Comment by paulobordignon** [comment]
Hi, @aldabil21 thanks for your response.

No, I suggest changing the field for example.

I have some custom fields like:
![image](https://github.com/aldabil21/react-scheduler/assets/24723164/ebac456e-829d-4877-aa06-d5dd4fb1df85)

I was trying to change the title 'Event 1' or another that I saved for another field like 'customer_name', 'admin_id'

**Comment by aldabil21** [comment]
You can use `eventRenderer` to render your own event item.
There is example sandbox in readme, search for Custom Event Renderer
