### ISSUE TITLE
Can you provide a description inside the event definition?

### ISSUE THREAD

**Issue by AttilioIurlaro** [aldabil21/react-scheduler#286]
![Cattura](https://github.com/aldabil21/react-scheduler/assets/34812000/bac21604-f0b1-46aa-84d2-e5ee12921203)
I want to pull more information inside this visualization when I click on the event.
It is possible?

Many thanks

**Comment by aldabil21** [comment]
Couple of options

1. You can use `viewerExtraComponent` to render your custom elements inside the popover, while keeping the internal header section.
2. You can use `customViewer` to overide the popover totally and make your own from scratch

Feel free to reopen if you still have issue

**Comment by AttilioIurlaro** [comment]
ok understood
But, How can I show the property value of each event?
This is the code:
`viewerExtraComponent={(<Typography variant='h6'>Note</Typography>)}`

I want to show the property value of the ProcessedEvent instead of "note"

**Comment by aldabil21** [comment]
it accepts a function or component.
you can do

```
viewerExtraComponent={(fields,event)=><SomeComponent /> }
```

**Comment by AttilioIurlaro** [comment]
Can you provide an example?
Many thanks

**Comment by AttilioIurlaro** [comment]
Many Thanks!
