### ISSUE TITLE
Disable hours grid in week and day views

### ISSUE THREAD

**Issue by alantygel** [aldabil21/react-scheduler#287]
Hi,
In my use case, there are mostly multi-day events. Even tough they have start and end hours, showing the hours grid is not very relevant. Thus, I would like to suggest an option to disable hours grid (or hours view) in Week and Day views.

In this case, one day events could appear as pillows, just like multi days events.

![image](https://github.com/aldabil21/react-scheduler/assets/1626935/89e2d944-efeb-471c-88b7-6105662fa262)

![image](https://github.com/aldabil21/react-scheduler/assets/1626935/30fb926c-6a3c-48db-a899-9b9a8f591b2e)

**Comment by cakonze** [comment]
I suggest not hiding all things, just the time column.
![image](https://github.com/aldabil21/react-scheduler/assets/8590713/9558e5ea-2ba9-4550-9b0a-eeca2343ad7b)

**Comment by aldabil21** [comment]
I'm working on an "Agenda" option view, that probably will resolve @alantygel's issue
For hiding the time column as @cakonze suggested , perhaps can simply add a prop for it

**Comment by vineettadakamalla** [comment]
@aldabil21 - Is the prop for hiding the time column available? I would like to use it in resource view.

**Comment by alantygel** [comment]
Hi,

Thanks for all the feedbacks! The agenda view is really, as it shows the events in a daily basis. The problem, in my use case, is that it changes completely the view logic, so using the normal view for month, and agenda view for week becomes not user friendly.

I'm working with events that last several day, and the start and hours are not very relevant (thought they exist).

So, the normal pillow view is perfect; and I would like to maintain my suggestion of an option for hidding the hour rows in the week view, to keep it consistent with the month view. In my use case, these rows keep empty most of the time, and when there is a one day event, it doesn't help very much.
