### ISSUE TITLE
Cell click opening event editor with editable = false

### ISSUE THREAD

**Issue by alantygel** [aldabil21/react-scheduler#288]
Hi,

It looks like after the last updates, cell click is firing the "New Event" dialog, even when `editable` prop is set to false.

![image](https://github.com/aldabil21/react-scheduler/assets/1626935/9b30405a-24b9-4916-9674-777c5e18eff5)

**Comment by aldabil21** [comment]
@alantygel double check if you are using an older version
The `editable` feature added in version https://github.com/aldabil21/react-scheduler/releases/tag/2.7.21

If you think this still is an issue, feel free to re-open
