### ISSUE TITLE
Adding a MUI Switch to the InputTypes

### ISSUE THREAD

**Issue by YannGory** [aldabil21/react-scheduler#289]
Hi,

Happy new year! 
Do you think it'll be possible to have a Switch InputTypes?
Today, I'm using a select with true or false values.

`
            <FormControlLabel
              labelPlacement="end"
              control={
                <Switch
                  checked={published}
                  onChange={togglePublished}
                />
              }
              label="Publish"
            />
`

It'd be like a Xmas present ;)

Thanks for all that scheduler module, it's awesome !

Best,

**Comment by aldabil21** [comment]
Hello 
I think in this case its better you setup up your own editor, check `customEditor` in the readme.
you can setup your own custom fields/validations etc

Feel free to re-open if you face any issues
