### ISSUE TITLE
Resource view remove redundant time column for every resource

### ISSUE THREAD

**Issue by vineettadakamalla** [aldabil21/react-scheduler#290]
Instead of duplicating the time display for every resource, is it possible to show fixed display of time on the left? It takes up a lot of real estate of duplicate the time when there are multiple resources.

![image](https://github.com/aldabil21/react-scheduler/assets/155585748/52bf9b89-0beb-4a6f-acec-465af4c63a2b)

Something like this 

![image](https://github.com/aldabil21/react-scheduler/assets/155585748/1f9cb5e5-d091-460a-9fd2-39d951345755)

**Comment by aldabil21** [comment]
Will close this as wontfix
you probably want to use the `tabs` options
