### ISSUE TITLE
customViewer still opens small box over event

### ISSUE THREAD

**Issue by gtchiudi** [aldabil21/react-scheduler#292]
Hello! I have a CustomViewer component that takes event prop. The component uses Dialog within it and handles the state in the component. My dialog closes properly, but there is still a small box that opens and does not close with my CustomViewer.  I'm not sure if it's an issue with my code or if it's internal. 
![image](https://github.com/aldabil21/react-scheduler/assets/57839440/5a3a9042-1855-4ba3-89f3-170d0f094870)
![image](https://github.com/aldabil21/react-scheduler/assets/57839440/ccc4409e-cec8-462b-96f5-b7c4959b50e5)
I have done a similar thing with the CustomEditor with no issue. I recognize that they function differently, but I'm not sure what I've done wrong.

**Comment by aldabil21** [comment]
Hi

`customViewer` uses `Popover` internally, Managing a `Dialog` on top of that is not recommended (2 layers on top of each other).
You should write your custom html, and it will automatically be managed to open/close within  the internal `Popover`.
something like:
```
  customViewer={(event) => {
          return (
            <div>
              <p>{`My Custom Viewer of ${event.title}`}</p>
              <p>{event.start.toISOString()}</p>
              <p>{event.end.toISOString()}</p>
            </div>
          );
        }}
```


If you for some reason, still want to use your `Dialog`, then make sure to also close the internal `Popover` when you close your own `Dialog`.
Something like:
```
        customViewer={(event, closeViewer) => {
          return (
            <CustomViewer event={event} onClose={closeViewer}  />
          );
        }}
```


Feel free to re-open if you still have issues
