### ISSUE TITLE
Padding issue on events 

### ISSUE THREAD

**Issue by vineettadakamalla** [aldabil21/react-scheduler#299]
I cannot figure out where this extra padding/whitespace is coming as we go from top to bottom. Any recommendation to get rid of it?
https://codesandbox.io/p/sandbox/standard-forked-7stzgw?file=%2Fpackage.json%3A4%2C21

Almost no whitespace in the events that start early
![image](https://github.com/aldabil21/react-scheduler/assets/155585748/91b4316c-c02c-4518-85e6-02e37d5249de)

Notice more whitespace on the events that are at the bottom. 
![image](https://github.com/aldabil21/react-scheduler/assets/155585748/cc8342b6-5389-4b7a-a11b-aea9fa2c1ac6)

On the sandbox, the whitespace is minimal, but in my project this is more apparent. Events are extending going into other timeslots. 
I added no css/customization, just using the basic scheduler from demo. 

![image](https://github.com/aldabil21/react-scheduler/assets/155585748/0bac9be7-453f-4e52-9c77-bf17c8440a3f)

**Comment by aldabil21** [comment]
The version of that sandbox was old before fixing this issue.

feel free to re-open if you still have issues
