### ISSUE TITLE
Add more width for the date column in agenda view

### ISSUE THREAD

**Issue by kztera** [aldabil21/react-scheduler#300]
As shown below, the date and day of the week column in Vietnamese looks quite odd because it is divided into 2 lines while the right column has a lot of empty space left. Max-width may need to be larger so that the date content is displayed in just 1 line.
Thank you for reading
![image](https://github.com/aldabil21/react-scheduler/assets/116504460/6603e933-fb66-47a2-9c94-04779986c52e)

**Comment by aldabil21** [comment]
Hi @kztera 
Did you solve this with the custom `headRenderer` ?
