### ISSUE TITLE
Extra padding on events

### ISSUE THREAD

**Issue by vineettadakamalla** [aldabil21/react-scheduler#303]
The version of that sandbox was old before fixing this issue.

feel free to re-open if you still have issues

_Originally posted by @aldabil21 in https://github.com/aldabil21/react-scheduler/issues/299#issuecomment-1900342132_

**Comment by aldabil21** [comment]
The example sandbox does not use ` <CssBaseline />`, which is needed.
Once used it will work properly

Please reply to this issue thread if you have further related issue, no need to open new issue. Thank you

**Comment by vineettadakamalla** [comment]
@aldabil21 - That did the trick. There is still minimal padding, but I can work with it. Thanks! 

Also, can you expose a prop to hide the time column. It is particularly useful in resource mode, since time column repeats for every resource and it is not mobile friendly.

**Comment by aldabil21** [comment]
This is requested before on #290
Soon hopefully
