### ISSUE TITLE
Change resources dynamically not working in latest versions

### ISSUE THREAD

**Issue by vineettadakamalla** [aldabil21/react-scheduler#304]
Looks like changing resources dynamically is broken in recent versions. 

https://codesandbox.io/p/sandbox/resources-forked-x726k7?file=%2Fpackage.json%3A11%2C36

**Comment by aldabil21** [comment]
Thats not how to change internal state since >= 2.7.3
use the `ref` to handle internal state, mentioned in readme

your sandbox should look like this https://codesandbox.io/p/sandbox/resources-forked-ntw655
