### ISSUE TITLE
Delete event when using customViewer

### ISSUE THREAD

**Issue by senhai-kun** [aldabil21/react-scheduler#308]
Any way to delete an event to the calendar when using a customViewer? 

<Scheduler 
    customViewer={(event, close) => (
          <EventViewer
              event={event}
              closeModal={close}
              {...otherProps}
          />
      )}
/>

const EventViewer = () => {

const handleDelete = async () => {
   // remote call delete
   const res = await deleteSchedule(event.event_id as string);
    // should also delete the event to calendar

    // then finally close the event viewer modal
    closeModal
}
// render
}

**Comment by paulobordignon** [comment]
Hi, @senhai-kun 

1 - You should pass the SchedulerRef to the customViewer function;
2 - Copy the original handleDelete function, and you can adapt to your reality:
https://github.dev/aldabil21/react-scheduler/blob/e446ab08ba5a6a51dd17fd40e5a3758263028f5c/src/lib/components/events/EventItemPopover.tsx
