### ISSUE TITLE
Agenda not getting disabled

### ISSUE THREAD

**Issue by senhai-kun** [aldabil21/react-scheduler#309]
Even if you added agenda={false} the agenda is still at the navigation and not being disabled

![image](https://github.com/aldabil21/react-scheduler/assets/95114113/5f9d5dce-b33d-45e7-9c39-319c02662064)

**Comment by vineettadakamalla** [comment]
@senhai-kun - Did you get this to work? I'm having the same issue.

**Comment by aldabil21** [comment]
It's still the case
this is a bug I will address soon

**Comment by senhai-kun** [comment]
> @senhai-kun - Did you get this to work? I'm having the same issue.

My only work around was disabling the navigation and create a custom one by navigating through ref but if this issue will be solved then cheers!
