### ISSUE TITLE
field date not working

### ISSUE THREAD

**Issue by D33-Team** [aldabil21/react-scheduler#31]
![20220802-062606](https://user-images.githubusercontent.com/98005370/182261677-4a676424-15f9-4ff3-929f-7d77ca9ed210.jpg)

**Comment by aldabil21** [comment]
As per the examlpe [sandbox here](https://codesandbox.io/s/custom-fields-b2kbv), I don't see issues.
If you can replicate this issue with a **sandbox** or **sample code**, I will be able to take a look at it.

**Comment by aldabil21** [comment]
I think its the same issue #33
