### ISSUE TITLE
onSelectedDateChange won't trigger when clicking on "More events..." in month view

### ISSUE THREAD

**Issue by kac5a** [aldabil21/react-scheduler#312]
Reproduce:

- Add an onSelectedDateChange function to log the selected date to the Scheduler
- Have multiple events on a day (3 at least) .
- In day view, navigate to a different date.
- Change to month view.
- On the original date, you'll see 2 events and a "More events..." button
- Click on the button
- The onSelectedDateChange will not trigger, only the onViewChange

I'm creating a different remote data solution for my project. I'm storing the selected date, view, and start-end dates in a state. Whenever I click on the more events button, the date is incorrect in my query, since it stores the last one selected, not the one that is currently shown.

**Comment by LasseKay** [comment]
Hello, i need this feature too :)
