### ISSUE TITLE
Feature Request: Option for disabling Dates

### ISSUE THREAD

**Issue by LasseKay** [aldabil21/react-scheduler#313]
hello and thank you for your great schedular :)

For my Projekt, i need an prop disabledDates which should be an array of objects which contains a date and a disabledColor as background for the cell. Nice to have is a onDisabledCellClick callback too.

Thanks in advance :)

Greetings,
Lasse

**Comment by aldabil21** [comment]
Hi
You can accomplish this with existing functionality, use `cellRenderer` to control what cell (or what day/time) should enabled/disabled.

Check this example sandbox: https://codesandbox.io/s/custom-cell-action-n02dv

Feel free to reopen if you still have an issue
