### ISSUE TITLE
event length === 0 when onDelete  

### ISSUE THREAD

**Issue by paweenacho** [aldabil21/react-scheduler#32]
I can not  get event when click onDelete

**Comment by aldabil21** [comment]
I'm not sure I fully understand what you want to achieve.
Can you explain more plz?
`onDelete` will get you the event id, like:
```
<Scheduler
   // ...
   onDelete={(id) => {
     // with the id you can delete the event from you db, and return a promise with the deleted id
    // or you can retrieve the event details from the `events` array
   }}
/>
```
Method signature [here](https://github.com/aldabil21/react-scheduler/blob/9e635b9c98d9b61ab17a1cfc9ffdb85ec723abee/src/lib/types.ts#L156)

**Comment by paweenacho** [comment]
Can I filter events by ID? I want to delete data in the database with refId. because in the database i don't store Id

**Comment by paweenacho** [comment]
great!! I can

Thank You ^_^
