### ISSUE TITLE
TypeError: (0 , r.createContext) is not a function on the latest NextJs

### ISSUE THREAD

**Issue by lunwhl** [aldabil21/react-scheduler#322]
I have this error when i run <Scheduler> in my page.tsx.

Anyone solve this issue?

**Comment by ph4rden** [comment]
I'm getting a TypeError: Cannot read properties of undefined (reading 'getTime') error

**Comment by aldabil21** [comment]
Hello

This calendar uses `Context` for state managment, either use `use client` directive or dynamic import the package https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#nextdynamic

Feel free to re-open if you still have an issue
