### ISSUE TITLE
Copy events while dragging

### ISSUE THREAD

**Issue by atheck** [aldabil21/react-scheduler#324]
Hi, when dragging an event and pressing the Ctrl key, the cursor changes to indicate a copy action. Is there a way to get this information in the `onEventDrop` callback?

**Comment by aldabil21** [comment]
in next release, the `onEventDrop` will include the `DragEvent`
you can get the info you need and more, new definition is like:

```
  onEventDrop?(
    event: DragEvent<HTMLButtonElement>,
    droppedOn: Date,
    updatedEvent: ProcessedEvent,
    originalEvent: ProcessedEvent
  ): Promise<ProcessedEvent | void>;
```

**Comment by atheck** [comment]
That's great. Thank you!
