### ISSUE TITLE
Is there a way to set resource to vertical resource orientation

### ISSUE THREAD

**Issue by kztera** [aldabil21/react-scheduler#326]
Currently, Resources are arranged horizontally (one next to another). So, how about vertical resource orientation (like under image). Will it be supported too?

![image](https://github.com/aldabil21/react-scheduler/assets/116504460/b570142b-e76e-4c58-a2b1-c422df00995b)

**Comment by aldabil21** [comment]
In next release, you can try `resourceViewMode="vertical"`

caveat: header days are not sticky for now

**Comment by kztera** [comment]
Great! Thank you for your support
