### ISSUE TITLE
Function(event). Helper function to render custom item in event item

### ISSUE THREAD

**Issue by kraffi83** [aldabil21/react-scheduler#327]
Hello @aldabil21,
thanks for the library.

Is it possible to add a prop wo replace the default EventItem?

[react-scheduler/src/lib/components/events/EventItem.tsx](https://github.com/aldabil21/react-scheduler/blob/e446ab08ba5a6a51dd17fd40e5a3758263028f5c/src/lib/components/events/EventItem.tsx)
Line 69

```typescript
let item = viewerItemComponent instanceof Function  ? viewerItemComponent(event)  : (
      <div style={{ padding: "2px 6px" }}>
        <Typography variant="subtitle2" style={{ fontSize: 12 }} noWrap>
          {event.title}
        </Typography>
        <Typography sx={{ fontSize: 11 }} noWrap>
            {hasNext ? (
              <NextArrow fontSize="small" sx={{ display: "flex" }} />
            ) : (
              showdate && !hideDates && format(event.end, hFormat, { locale })
            )}
          </Typography>
        </div>
    );
```

**Comment by RosenTomov** [comment]
Hello,
you can use `eventRenderer` prop to pass a custom event component (doesn't apply to multi-day events and monthly view https://github.com/aldabil21/react-scheduler/blob/e446ab08ba5a6a51dd17fd40e5a3758263028f5c/src/lib/components/events/EventItem.tsx#L58)

e.g.
```
<Scheduler
...
eventRenderer={({ event, onClick }) =>  
    <YourEventComponent
	data={event}
	onClickFn={onClick}
    />
}
...
/>
```

**Comment by kraffi83** [comment]
Hello,
thx this works for me
