### ISSUE TITLE
Feature request: Disable viewer popper completely

### ISSUE THREAD

**Issue by marcauberer** [aldabil21/react-scheduler#329]
Hi,
first of all thank for the awesome library!
I have a feature request: I have the use case where the user clicks on a calendar event and gets redirected to a different view. Currently, I use the `onEventClick` callback to navigate to the new view and use this as a hack to get rid of the unwanted popper:

```
customViewer={(_event, close) => {
  setTimeout(function () {
    close();
  }, 50);
}}
```

This seems not very good to me and could lead to race conditions.

Could you introduce a property, say `disableViewer: boolean` that disables the viewer popper completely?

**Comment by aldabil21** [comment]
Hi

you can use `disableViewer` prop in next release

**Comment by marcauberer** [comment]
Thanks!

**Comment by marcauberer** [comment]
@aldabil21 Just tried it out. I have to mention one shortcoming: If the `disableViewer` option is set, the onEventClick callback does not fire. Could you fix that?

**Comment by slash-84** [comment]
@marcauberer try with version 2.8.4 that enables the use of `onEventClick` with `disableViewer`. https://github.com/aldabil21/react-scheduler/pull/338

**Comment by marcauberer** [comment]
Will do, thanks!

**Comment by marcauberer** [comment]
@aldabil21 @slash-84 `onEventClick` works now, but the viewer is still showing when agenda view is active. Can you fix that as well?

**Comment by slash-84** [comment]
i created https://github.com/aldabil21/react-scheduler/pull/340
