### ISSUE TITLE
Todos: Recurring Events

### ISSUE THREAD

**Issue by ph4rden** [aldabil21/react-scheduler#337]
I see recurring events is something planned, is there a timeline for this feature? Thank you for the library, it's been very helpful.

**Comment by ryeact-dev** [comment]
I am also waiting for this feature

**Comment by javargasm** [comment]
I am also waiting for this feature

**Comment by marcauberer** [comment]
I would also have interest

**Comment by aldabil21** [comment]
Recurring Events in version `2.9.4`, thanks to @marcauberer

**Comment by devth** [comment]
This is awesome! Any docs or demos how to use it?
