### ISSUE TITLE
Problem with Firefox 

### ISSUE THREAD

**Issue by Sitaras** [aldabil21/react-scheduler#34]
"Invalid interval."
Only at Firefox browser.
![image](https://user-images.githubusercontent.com/45051550/182582537-e1643fe9-0a99-40ef-8094-2c32b3e68de9.png)

**Comment by aldabil21** [comment]
Your description of the issue, as well as the error message are not helpful.

However, **Invalid Interval** is an error where you make mistake with time range.
For example, you put a `endHour` before `startHour` which is invalid, and currently there is no validation for that.
So make sure you review your `startHour` & `endHour`, known that the `DayHours` type is a number from 0-23. There is no 24.

if you still have an issue, provide more details:
1. Firfox version
2. Your sample code
