### ISSUE TITLE
edit event card 

### ISSUE THREAD

**Issue by omarKenawi** [aldabil21/react-scheduler#351]
when any event be clicked a event card apper how to custom this card to apper another data like location 
here is my code `import { Scheduler } from "@aldabil/react-scheduler";

function ViewSchedule() {
  const initialEvents = [
    {
      event_id: 1,
      title: "Event 1",
      start: new Date("2024/4/13 09:30"),
      end: new Date("2024/4/13 11:30"),
      location: "modarag 10",
    },
    {
      event_id: 2,
      title: "Event 2",
      start: new Date("2024/4/13 11:30"),
      end: new Date("2024/4/13 12:30"),
      color: "red",
      location: "modarag 5",
    },
    {
      event_id: 3,
      title: "Event 3",
      start: new Date("2024/4/13 17:30"),
      end: new Date("2024/4/13 18:30"),
      location: "modarag 2",
    },
    {
      event_id: 4,
      title: "Event 4",
      start: new Date("2024/4/13 15:30"),
      end: new Date("2024/4/13 18:30"),
      color: "red",
      location: "modarag 9",
    },
  ];
  return (
    <Scheduler
      agenda={false}
      month={null}
      day={{
        startHour: 7,
        endHour: 20,
        step: 60,
        navigation: true,
      }}
      view="week"
      week={{
        weekDays: [0, 1, 2, 3, 4, 5],
        weekStartOn: 6,
        startHour: 7,
        endHour: 20,
        step: 60,
        navigation: true,
        disableGoToDay: true,
      }}
      deletable={false}
      draggable={false}
      editable={false}
      disableViewer={false}
      hourFormat="12"
      events={initialEvents}
    />
  );
}

export default ViewSchedule;
`

**Comment by aldabil21** [comment]
Search in the ReadMe for the word "viewer", you will see all configurations related to it
