### ISSUE TITLE
Full Day Event Bug

### ISSUE THREAD

**Issue by kraffi83** [aldabil21/react-scheduler#357]
Hello everyone,

In Version 2.9.x the Scheduler can´t show Full-Day Events in Week and Day View.

See v.2.8.8
https://codesandbox.io/p/sandbox/standard-forked-zssfs7
and v. 2.9.0
https://codesandbox.io/p/sandbox/standard-forked-3qrhs5

Best regards

**Comment by slash-84** [comment]
@aldabil21 I have a PR proposal.

I found another bug both 2.8.x and 2.9.x: in agenda view events are being duplicated using dates in the above codesandbox. I think this happens because the end Date trails to midnight.

Could you have a look?

**Comment by aldabil21** [comment]
Thank you @slash-84 
The agends issue resolved as well
