### ISSUE TITLE
Getting TypeError: e.start.getTime is not a function when passing the events. 

### ISSUE THREAD

**Issue by zdnearchou** [aldabil21/react-scheduler#360]
Hello when i'm passing the events props i get this error: TypeError: e.start.getTime is not a function. Here's a sample of the objects from the array...

{
    "event_id": 300905,
    "title": "Event 1",
    "start": "2024-07-31T12:00:00.000Z",
    "end": "2024-07-31T14:00:00.000Z"
}

**Comment by slash-84** [comment]
You are passing `start` and `end` as `string`, they must be `Date`
