### ISSUE TITLE
Wrong events offset

### ISSUE THREAD

**Issue by kelf47** [aldabil21/react-scheduler#363]
The height of the event gets a higher offset the lower it is.

![image](https://github.com/aldabil21/react-scheduler/assets/2972781/6b3a8e4a-c224-43a2-8fd7-057c59dc0345)

![Screenshot from 2024-05-09 16-24-58](https://github.com/aldabil21/react-scheduler/assets/2972781/25bc35d3-17c9-4413-9916-84bc5a275311)

**Comment by kelf47** [comment]
I'm using  @aldabil/react-scheduler@2.9.2

**Comment by kapilsahitya** [comment]
I am facing the Same issues, Please Help me in this, 
Thanks in advance

**Comment by slash-84** [comment]
@kelf47 @kapilsahitya can you reproduce the bug on https://codesandbox.io/ ?

**Comment by aldabil21** [comment]
Hey
This seems to be like #208 
feel free to reopen if you think its still an issue
