### ISSUE TITLE
How to prevent going to first resource field after onConfirm?

### ISSUE THREAD

**Issue by IIRobotNinjaII** [aldabil21/react-scheduler#366]
Hey after using a customEditor, and I am creating a new event on a different resource which is not the first resource after onConfirm, it navigates to the first resource and I have to manually go to the resource to which the new event was added. Is there a way to stay on the same resource after a new event is added?

The same issue was spotted in the sandbox given in the demos - https://codesandbox.io/s/resources-7wlcy

Thank You

**Comment by masulo1212** [comment]
same problem
