### ISSUE TITLE
Get current calendar start and end dates

### ISSUE THREAD

**Issue by Gromov812** [aldabil21/react-scheduler#369]
Hello, Abdulraoof! First of all, I want to thank you for a great job! I am looking for a solution to my question, could you help me? I need to get the start and end dates of the available calendar cells in order to dynamically request events for this period from server and update them in the calendar. For example, by default, the calendar opens for the month from May 1st to May 31st, how can I get these dates?
Thanks in advance for the answer!

**Comment by aldabil21** [comment]
Hi
The getRemoteEvents specifically made for this. You will have dynamic query every time the calendar changes view, dates etc…

**Comment by Gromov812** [comment]
Sir, thank you so much!
