### ISSUE TITLE
How to change the colours and edit the topbar?

### ISSUE THREAD

**Issue by shariandabre** [aldabil21/react-scheduler#370]
I want the background to adapt to dark mode but I am not able to find any way to change the style. Can anyone help me?

**Comment by aldabil21** [comment]
The theme is extracted from MUI theme setup.
The scheduler is just a bunch of Mui Paper and Button components.
Adjust your Mui theme setup and the Scheduler will respect that.
If you a more specific issues, feel free to reopen with specific details
