### ISSUE TITLE
Custom event render is not work in month view 

### ISSUE THREAD

**Issue by omar199523** [aldabil21/react-scheduler#376]
I work in this library and add event render and work in day and week view but not working in month view

**Comment by aldabil21** [comment]
Are you sure it's not hidden under the "read more"? 
can you provide example sandbox? This is a basic setup example and I can add events in month view: https://codesandbox.io/p/sandbox/standard-x24pq

**Comment by omar199523** [comment]
This page is not present

في السبت، ١٥ يونيو ٢٠٢٤ ١٠:٥١ ص Abdulraoof ***@***.***> كتب:

**Comment by aldabil21** [comment]
You can find the basic demo in the readme
