### ISSUE TITLE
Issue with MUI Datepicker

### ISSUE THREAD

**Issue by ValerieMichaud** [aldabil21/react-scheduler#38]
I currently have this version of mui/labs and the date pickers doesn't show up when I'm editing an event.
The date also doesn't show up on the top left corner.

"@aldabil/react-scheduler": "^2.2.2",
"@emotion/react": "^11.9.3",
"@emotion/styled": "^11.9.3",
"@mui/icons-material": "^5.8.4",
"@mui/lab": "^5.0.0-alpha.85",
"@mui/material": "^5.9.1",
"@mui/styled-engine-sc": "^5.8.0",
"@mui/x-date-pickers": "^5.0.0-beta.4"

I see in your sandbox that the version is different and I get a warning when putting my versions into a [forked sandbox](https://codesandbox.io/s/standard-forked-ie49xn):

"@aldabil/react-scheduler": "2.1.0",
"@emotion/react": "11.7.1",
"@emotion/styled": "11.6.0",
"@mui/icons-material": "5.2.5",
"@mui/lab": "5.0.0-alpha.61",
"@mui/material": "5.2.5",
"date-fns": "2.21.2",
"react": "17.0.0",
"react-dom": "17.0.0",
"react-scripts": "4.0.3"

MUI: The LocalizationProvider component was moved from `@mui/lab` to `@mui/x-date-pickers`.
You should use `import { LocalizationProvider } from '@mui/x-date-pickers'`
or `import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider'`
More information about this migration on our blog: https://mui.com/blog/lab-date-pickers-to-mui-x/. 
    in DeprecatedLocalizationProvider (created by oe)
    in oe (created by Oe)
    in Oe (created by fe)
    in fe (created by qe)
    in qe (created by Ne)
    in Ne (created by App)
    in App

**Comment by aldabil21** [comment]
Please check #33 
Re-open if it doesn't solve the issue.
