### ISSUE TITLE
Agenda view missing on click function for events

### ISSUE THREAD

**Issue by PatrikZajacMia** [aldabil21/react-scheduler#381]

**Comment by aldabil21** [comment]
In the [basic example sandbox](https://codesandbox.io/p/sandbox/standard-x24pqk), the `onEventClick` seems to be triggered on agenda item click.
do you have more details to share? or sample sandbox?

**Comment by PatrikZajacMia** [comment]
@aldabil21 Problem is maybe in that im using `eventRenderer` and even when i spread `props` to div its not triggering `onEventClick` function

**Comment by aldabil21** [comment]
@PatrikZajacMia Since you are using `eventRenderer` to render your custom element, then you have full control. use the `onClick` on your custom element, you don't need the `onEventClick`
