### ISSUE TITLE
Scheduler state changes

### ISSUE THREAD

**Issue by vineettadakamalla** [aldabil21/react-scheduler#382]
Hi,

I'm setting a custom property in UseEffect whenever date changes on the scheduler. I'm accessing this property in the EventClick method. This works when the scheduler is initially loaded for today's date. But when I change the date, then useEffect is called, but the custom property is no longer available on the calendarRef. Not sure if I'm following the correct pattern. 

useEffect(() => {
.....
calendarRef.current.scheduler.handleState(
                customData,
                "customProp"
            );
.....
}, [selectedDate]);

const handleEventClick = async (event) => {
        var data= calendarRef.current?.scheduler.customProp;  ---->Correctly available on initial date, empty on date change.

**Comment by aldabil21** [comment]
I want to make sure I got this correct @vineettadakamalla 

When you say “customProp”, do you actually mean it literally? Or just as example?

**Comment by vineettadakamalla** [comment]
Just an example @aldabil21. My actual prop name is "reservations" and it has array of objects.

**Comment by aldabil21** [comment]
You can not hijack the internal state of the Scheduler, the Scheduler component wil re-render at some point and revalidate the current state. The `handleState` should only accepts the defined keys/value specified in the [props](https://github.com/aldabil21/react-scheduler?tab=readme-ov-file#scheduler-props).

The question is: why you want to save some state inside the Scheduler component that the **Scheduler it self will never use**, why not save it in your component state?

What are you trying to achieve, perhaps it can be done in another way.

**Comment by vineettadakamalla** [comment]
Initially I had it in my component state, but the issue I was facing is that the updated state was not available inside the EventRenderer function. I have a button inside the eventrenderer function and the state is retrieved in the onclick event. It works on the initial render, but when the state changes the onclick event was still getting the old state value.

**Comment by aldabil21** [comment]
Create minimal example of what you want to achieve in a sandbox and we can better help with this
