### ISSUE TITLE
Use with Mantine styles event gets offset

### ISSUE THREAD

**Issue by MariuzM** [aldabil21/react-scheduler#384]
When i create event and move it down the list it get more and more offset 
i noticed this when i have my project with `import '@mantine/core/styles.css'` 

<img width="548" alt="image" src="https://github.com/user-attachments/assets/d48bbca4-ec98-4833-8f90-34b1c98e0d7a">
<img width="702" alt="image" src="https://github.com/user-attachments/assets/903d3636-fd78-4cc6-960e-cff3d2c443b5">

I have tried reseting css for this component and it fixed the issue but now i can't move the event 
<img width="726" alt="image" src="https://github.com/user-attachments/assets/69ae762b-2915-43e2-b196-3d9cf67c9b40">

**Comment by aldabil21** [comment]
That CSS overriding the box-sizing, see #197

This Scheduler kinda made for Mui, see the first note in the ReadMe
