### ISSUE TITLE
eventRenderer function trigger issue 

### ISSUE THREAD

**Issue by HirenBathani** [aldabil21/react-scheduler#387]
1. The eventRenderer function is called when switching between day and week views, but it is not triggered for the month view. Why is this happening?

2. When I change the view mode, I use the getRemoteEvents function to set the mode. However, inside the eventRenderer function, the correct mode data is not being received. How can I ensure that the eventRenderer function gets the correct mode data?

Please provide proper suggestions.

**Comment by aldabil21** [comment]
1. Is mentioned here #314

2.
> inside the eventRenderer function, the correct mode data is not being received

the `eventRenderer` does not have `view` property. You can access the view/mode propery from the internal state using the `SchedulerRef`. however you still cannot override the month event. For the reason mentioned in the issue above.
