### ISSUE TITLE
Access selected date outside of query

### ISSUE THREAD

**Issue by hmaiermack** [aldabil21/react-scheduler#39]
Sorry if this is already possible, but it would be great to have access to the current view date outside of the provided query in remoteEvents. Perhaps by providing a context provider alongside the Scheduler component?

**Comment by aldabil21** [comment]
You can do that now if you upgrade to 2.3.0
you can control the `selectedDate` prop from within your component state.
For ex:
```
// ....
const [date, setDate] = React.useState(new Date());

return (
    <div>
      <button onClick={() => setDate(/* Change to tommorow in your preferred way*/)}>
        Go To Tommorow
      </button>
      <Scheduler
        // ....
        selectedDate={date}
      />
    </div>
  );
```

Is that what you looking for? Let me know.

Note that in 2.3 `@mui` deps changed and you need `@mui/x-date-pickers` instead of the old `@mui/lab`

**Comment by hmaiermack** [comment]
In this example is Scheduler still rendering the Navigation with the buttons? If so that would mean we're rendering our own button as well as the ones included in the Scheduler component, correct? In that case it might be better to pass the update handler directly to the button within Scheduler. With all the different view possibilities it may make more sense to provide the date via context rather than making the user define their own handling logic for each change (+/- day, +/- week, +/- month etc), unless you want to go in a more headless direction.

**Comment by aldabil21** [comment]
I think if you tell me what's your use-case exactly and you want to accomplish, It would be easier for me to help.

**Comment by hmaiermack** [comment]
Sure, all I want is to access the date outside of the scheduler component, to use in a React Query query via trpc. The example you provided will definitely work for that. I'm just curious if I'm able to use the existing functionality to change the date of the scheduler component while having the date exposed outside of that component. Sorry for not being more clear!

**Comment by aldabil21** [comment]
So I think you want something like a _setter_ method to set internal state of the calendar. It can be exposed, but not sure is it needed?
if you:
1. Have the exact specific date range query according to calendar view, with the help of `remoteEvents`
2. Have the current date in hand with the help of `selectedDate`, and you now can _change the date of the scheduler component while having the selectedDate exposed_

What more can be provided in regard of _date_ aspect that will give more help to you, can you elaborate more?

**Comment by hmaiermack** [comment]
1. You aren't able to call hooks from within remoteEvents, meaning something like React Query isn't usable inside of it.
2. This behavior is totally fine, however in your earlier example it will render both my custom button as well as the buttons inside of React-Scheduler's Navigation component if I'm understanding it. Please correct me if I'm wrong.
```js
// ....
const [date, setDate] = React.useState(new Date());

return (
    <div>
      // this will render a Button which allows you to control selectedDate, which is what we want
      <button onClick={() => setDate(/* Change to tommorow in your preferred way*/)}>
        Go To Tommorow
      </button>

       // <Scheduler /> will also render buttons that control selectedDate
       // rendering both doesn't make sense
      <Scheduler
        // ....
        selectedDate={date}
      />
    </div>
  );
```

Again, please correct me if I'm misunderstanding!

What I'm imagining is accessing the selectedDate from context, without having to change any of the built in functionality that you're already providing.

```js
// ...
   // something like this
   const selectedDate = useSchedulerContext()
   const { data } = useQuery(url, { selectedDate})

   <Scheduler
      remoteEvents={data}
   />
```

Understandable if you don't want to provide this behavior in the second example, however in the first example we don't want to render our own buttons alongside the buttons rendered by the <Scheduler />component.

Thanks so much for your work btw the component is great to work with!

**Comment by hmaiermack** [comment]
Also, looks like there may be an issue in the peer deps after the most recent update
may need "@mui/x-date-pickers": ">=5.0.0-beta" 
```
npm i @aldabil/react-scheduler

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @aldabil/react-scheduler@2.3.0
npm WARN Found: @mui/x-date-pickers@undefined
npm WARN node_modules/@mui/x-date-pickers
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @mui/x-date-pickers@">=5.0.0" from @aldabil/react-scheduler@2.3.0
npm WARN node_modules/@aldabil/react-scheduler
npm WARN   @aldabil/react-scheduler@"*" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @mui/x-date-pickers@>=5.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

```

**Comment by aldabil21** [comment]
Fair points. I will look into it.

In point 2, yeh it doesn't make sense to put 2 navigation buttons. It was just an example to show that date can be changed dynamically from outside.

**Comment by aldabil21** [comment]
Unfortenutly, won't work unless adding sort of HOC or context wrapper to be wrapped around your component.
I might think about adding this feature.

For now, I think the feasible solution is to use the `query` provided on navigation, it's more accurate than using the `selectedDate`, since it gives you a range depending on the view.

For ex:
```
  const queryClient = useQueryClient();
  
  const onNavigate = async (query: string) => {
    // const q = new URLSearchParams(query);
    // const start = q.get("start");
    // const end = q.get("end");
    const data = await queryClient.fetchQuery([/** Set your query */])
    return data;
  };

  // ...

  return (
    <div>
      <Scheduler
         // ...
        remoteEvents={onNavigate}
      />
    </div>
  );
```


though, suggestions and PRs are welcome if you have an implementation that can get you the solution you like.
