### ISSUE TITLE
Custom event component in month view.

### ISSUE THREAD

**Issue by his-maj-esty** [aldabil21/react-scheduler#396]
I need custom event component in month view. After inspecting through the code, I saw it is intentionally disabled. Can you add support for that.

**Comment by aldabil21** [comment]
This explained here #314
You can use the custom `sx` and create your title, what else you wanna override in that tiny bar?
Can you share how would you override it and how it would be displayed?

**Comment by his-maj-esty** [comment]
I want to display a icon and text

**Comment by aldabil21** [comment]
`title` accepts JSX in 2.9.5, which solves this card
