### ISSUE TITLE
Timezone setup

### ISSUE THREAD

**Issue by Aishwarya-Venkatraman** [aldabil21/react-scheduler#41]
How to set timezone for the scheduler to use timezone other than the local system / browser?

**Comment by aldabil21** [comment]
Unfortunately, no option for that in the current setup.

**Comment by borstelmannl** [comment]
@aldabil21 will there be timezone support in the future?

**Comment by aldabil21** [comment]
@borstelmannl Honestly, I don't have a plan for this yet. But it's in the list of todos

**Comment by Bhuwan-Buda** [comment]
Why day view is not working properly ? 
Error: Uncaught TypeError: Cannot assign to read only property '0' of object '[object Array]'  appears if I choose day view in navigation.
