### ISSUE TITLE
Strange margin for custom ViewerExtraComponent 

### ISSUE THREAD

**Issue by jucopera** [aldabil21/react-scheduler#50]
Hi @aldabil21 , when I used prop `ViewerExtraComponent` and add some nodes, there is a wrong width appeared on 'EventItem'.

If a child of ViewerExtraComponent is a long string or a flexible box contained multiple lines,  the width of the event view was stretched. 

[Expected Behavior] 
Styles of extra view are correct.

[Actual Behavior]
There is a strange margin assigned to 'PopverInner'.
The reason why the event view was stretched is  'max-width: 95%' assigned to itself. When I dropped it, styles would be correct.
You can see this [case](https://codesandbox.io/s/customeditor-forked-0guoqg)

And I found noway to add props to change the root style for 'EventItem', I had to add  a hard css code below to fix it provisionally:

` body
            > div.MuiPopover-root.MuiModal-root
            > div.MuiPaper-root.MuiPaper-elevation.MuiPaper-rounded.MuiPaper-elevation8.MuiPopover-paper
            > div {
            max-width: none;
          }`

Could you remove the 'max-width' attribute or provider some methods to change styles for `EventItem` 😀? 
Thanks.

**Comment by aldabil21** [comment]
You are absolutely right @jucopera 
it meant to be the other way around, a limited max width not a min width.

Try the release after #51 it should solve it
