### ISSUE TITLE
Button to change view language

### ISSUE THREAD

**Issue by luizfilho** [aldabil21/react-scheduler#52]
Hello!! 

This buttons, don't follow the locale. 

<img width="269" alt="Screen Shot 2022-10-16 at 22 54 25" src="https://user-images.githubusercontent.com/31169925/196072831-8cafd468-f3a1-4822-8e7a-ea16404ec0f6.png">

**Comment by aldabil21** [comment]
Hi

Localization is not done in some part as stated in the ReadMe.
These values are hard-coded now in the [navigation component](https://github.com/aldabil21/react-scheduler/blob/a76bddaded5e2d74f828322f31958981bb1befd7/src/lib/components/nav/Navigation.tsx#L53) 

You are welcome to PR a solution for localization. The idea is to pass a prop ob an object to make the user fill in the strings, like:
```
<Scheduler
// ...
translations={{
   navigation:{
      today:"今天",
      Month:"月",
      // ...
    },
  form:{
     confirm: "??",
     cancel: "??"
  }
}}
// ...
```

**Comment by senegoid** [comment]
@luizfilho se quiser uma tradução rápida hard-coded tem aqui:
https://github.com/senegoid/react-scheduler

**Comment by aldabil21** [comment]
Hi @senegoid 
below is basically the main idea which could be done. Then you can pull out the translations from the state. 
IF you can PR that would be awesome!

> 
> Localization is not done in some part as stated in the ReadMe. These values are hard-coded now in the [navigation component](https://github.com/aldabil21/react-scheduler/blob/a76bddaded5e2d74f828322f31958981bb1befd7/src/lib/components/nav/Navigation.tsx#L53)
> 
> You are welcome to PR a solution for localization. The idea is to pass a prop ob an object to make the user fill in the strings, like:
> 
> ```
> <Scheduler
> // ...
> translations={{
>    navigation:{
>       today:"今天",
>       Month:"月",
>       // ...
>     },
>   form:{
>      confirm: "??",
>      cancel: "??"
>   }
> }}
> // ...
> ```

**Comment by senegoid** [comment]
Done #54

**Comment by luizfilho** [comment]
Thanks!! @senegoid and @aldabil21
