### ISSUE TITLE
add more fields to the customEditor

### ISSUE THREAD

**Issue by KsenyaD** [aldabil21/react-scheduler#53]
Could you tell me, how to add more fields to the customEditor?

I need more fields when editing to the customEditor. Now only comes interface CalendarEvent

**Comment by aldabil21** [comment]
Though, you can use `props.loading(true/false)` and `props.close()` to control the modal.

If that still not clear yet, share a sandbox of what you try to implement and I can look into it

**Comment by aldabil21** [comment]
Re-open if you face issues
