### ISSUE TITLE
Disabled Date/Time Ranges ?

### ISSUE THREAD

**Issue by jktan-arrivo** [aldabil21/react-scheduler#59]
Hi I would like to ask can we have some disabled Date/Time Ranges feature ?

**Comment by aldabil21** [comment]
Do you mean in the calendar grid? or the date navigator?
if you could elaborate more plz

**Comment by aldabil21** [comment]
Assume you found solution.

**Comment by jktan-arrivo** [comment]
Yes, sorry for late reply.

disabled in the calendar grid that user cannot click those specific date and time ranges

**Comment by jktan-arrivo** [comment]
![Screen Shot 2022-11-03 at 3 32 38 PM](https://user-images.githubusercontent.com/109949861/199667681-da6ccfec-0e94-4c3d-88cb-2d889ed5d643.png)

I havent found the solution yet.

**Comment by aldabil21** [comment]
Have you checked out this example [sandbox](https://codesandbox.io/s/custom-cell-action-n02dv) in the Readme?

does it solve your issue?

**Comment by jktan-arrivo** [comment]
@aldabil21 thanks

I am really appreciated for your help.

This is really what I want.
