### ISSUE TITLE
Event wrong height

### ISSUE THREAD

**Issue by vpachedzhi** [aldabil21/react-scheduler#6]
In the [Basic example](https://codesandbox.io/s/react-scheduler-demo-standard-v96bd) if we add an event(the **test** one) having start time 9am and end time 6 pm, the blue rectangle does not touch the bottom end of the last cell

![image](https://user-images.githubusercontent.com/12788097/145060106-043ed8f3-6e0f-47b7-a720-c312711b35a1.png)

**Comment by aldabil21** [comment]
Hi,
You are right.
There are some missing height calculations that makes this behaviour (shorter height) in the day/week views.
I haven't figure that out in the time I made it, I left it as is, cuz I'm planning to refactor the CSS part, some day... I left a note about it when I was working on it here
https://github.com/aldabil21/react-scheduler/blob/cd196878c64abf21e693b7303d566dc87e720edb/src/lib/components/events/TodayEvents.tsx#L38

For the second part, the 1 Day (all day) event is not possible in the current setup, the top section is for "multi-days" when total days are > 1. This work was designed for a project for a company that has a fixed calendar from 8am to 6pm each event is no more than 1h, so a lots of aspects wasn't in mind, Im sorry about that.
