### ISSUE TITLE
State change in parent component resets selected date

### ISSUE THREAD

**Issue by jackstenglein** [aldabil21/react-scheduler#61]
Hello, I am creating a component that displays a set of filters next to the scheduler. When one of the filters is checked/unchecked, that changes which events are passed to the scheduler's events field. However, it also resets the scheduler back to the current date. 

As an example, I have the following flow: 
1. User opens the page and scheduler is in week format on the current date.
2. User clicks the scheduler navigation button to navigate to the next week. 
3. User changes the filter values

I want this to remain on the next week and simply hide/show some new events. Instead, the scheduler reverts back to the current date and the user has to click to the next week again in order to see the changed events.

It seems like changing any state in the parent component resets the scheduler back to the current date. Is there a way to prevent this from happening?

**Comment by jackstenglein** [comment]
As an update, I have created a code sandbox demonstrating the problem here: https://codesandbox.io/s/event-update-resets-date-2grbbs?file=/src/App.js

The problem only occurs when the state change results in a change to the events parameter. If the state change is unrelated, then the problem does not occur.

**Comment by aldabil21** [comment]
Hi @jackstenglein 

Thank you for the sandbox it made it easier. You are right. and there is a history to this #39 

it turns out the exposing `selectedDate` in this way is not a good solution, so I think I will revert it back, and find another better solution for #39 

You can use next release to see this issue fixed

**Comment by aldabil21** [comment]
Try v2.5.4

Feel free to reopen if you still find issues

**Comment by jackstenglein** [comment]
@aldabil21 Thanks, that fixed the issue. One possible solution to both this and #39 is to expose a selectedDate and onDateChange prop. Then the parent component can be notified of when the date changes and update the selected date in their own state. IE make it a controlled field, similar to the value of a MUI TextField.

**Comment by aldabil21** [comment]
You are right.

That would work as well.
