### ISSUE TITLE
Disable Edit and Delete Buttons

### ISSUE THREAD

**Issue by Sitaras** [aldabil21/react-scheduler#62]
![image](https://user-images.githubusercontent.com/45051550/199752862-ea9fcf5d-84df-4476-9bdb-fddae84ff320.png)

Can I disable (or disappear) somehow these two buttons ?

**Comment by aldabil21** [comment]
Yes

Look for `editable' & `deletable` props in the Readme, they are available calendar-wise and event-wise, with priority to event-wise option.
