### ISSUE TITLE
Calendar View Mode

### ISSUE THREAD

**Issue by Sitaras** [aldabil21/react-scheduler#64]
Ιs there any way to disable Add, Delete and Update?
I want only to see the events and their details.

**Comment by aldabil21** [comment]
Read the ReadMe

**Comment by Sitaras** [comment]
I open this issue because I didn't see this functionality at ReadMe.
I only found these options: 

draggable={false}
editable={false}
deletable={false}

So, if I tap somewhere that doesn't have an event then a modal will open.

**Comment by aldabil21** [comment]
In this case, use `cellRenderer`, example [Custom Cell Action](https://codesandbox.io/s/custom-cell-action-n02dv)

**Comment by Sitaras** [comment]
Thanks !
