### ISSUE TITLE
Show indicator of current time?

### ISSUE THREAD

**Issue by jackstenglein** [aldabil21/react-scheduler#65]
Would it be possible to get a horizontal line drawn in the cells showing the current time (like in Google Calendar)? I think this would only make sense to show when in the week view or the day view. Here is a screenshot of what I am referring to:

<img width="1421" alt="Screen Shot 2022-11-04 at 10 47 57 AM" src="https://user-images.githubusercontent.com/22841845/200018415-ecb9e352-9456-4fca-beb4-be46d96bc7ec.png">

I'm not sure how difficult this is to implement, but I'd be happy to work on this and send a pull request if I had some guidance on which files to work with.

**Comment by aldabil21** [comment]
That would be nice feature. PRs are welcome.

I would put it in the `TodayEvents` component, before mapping the `todayEvents` array, this component only rendered in week/days view and has all the data needed.

there, check if `today` is actually today using `isToday()` or whatever method you prefer, then render the new "CurrentTimeBar" component or whatever you name it, there you would figure our the `top` css value using `startHour` compared to the current time, and take into considration the `minuteHeight` factor.

you would optinally, maybe put an interval to change/recalculate the css `top` value.

Thats my imagination in a glance. But you are welcome to submit your implementation after you play with it & test it.
