### ISSUE TITLE
why the current day disappear in other views?

### ISSUE THREAD

**Issue by luizfilho** [aldabil21/react-scheduler#66]
I can add the current day in others views, and put de indicator feature mentioned in this [issue](https://github.com/aldabil21/react-scheduler/issues/65) ?

**Comment by luizfilho** [comment]
Using `weekDays` resolve this problem.

<img width="395" alt="Screenshot 2022-11-04 at 15 04 30" src="https://user-images.githubusercontent.com/31169925/200045118-99155357-348f-4940-80d3-752488683755.png">

**Comment by aldabil21** [comment]
Yeh. It's because **friday** in our holiday here, maybe I shouldn't make the default configuration kinda personal lol

**Comment by luizfilho** [comment]
heheh by default in my opnion, should be like the print that I sended.
