### ISSUE TITLE
Feature for min and max Date

### ISSUE THREAD

**Issue by Sitaras** [aldabil21/react-scheduler#68]
![image](https://user-images.githubusercontent.com/45051550/200134538-1d7bdc4e-6ae5-43f0-9f5f-c7fcf56cc68d.png)
Feature to limit the dates range (min and max Dates)

**Comment by Sitaras** [comment]
How I can display only 2021 and 2022? 
![image](https://user-images.githubusercontent.com/45051550/203945815-76d72aba-6234-4a3c-aced-2a4770f2ecbd.png)

**Comment by aldabil21** [comment]
use `navigationPickerProps` to setup your min/max conditions, refer to https://mui.com/x/api/date-pickers/calendar-picker

**Comment by Sitaras** [comment]
Can you provide me a small example here ?
Thanks

**Comment by Sitaras** [comment]
Also "buttons" at navigation aren't clickable after the update
![image](https://user-images.githubusercontent.com/45051550/203955733-70b06962-7a75-482c-8489-920d187d2087.png)

**Comment by aldabil21** [comment]
```js
 navigationPickerProps={{
        minDate: new Date(2021, 0, 1),
        maxDate: new Date(2022, 11, 31),
 }}
```

**Comment by aldabil21** [comment]
If there is new issue plz open a new issue so I can track.
