### ISSUE TITLE
Events are rendered in wrong timeslot due to daylight savings

### ISSUE THREAD

**Issue by jackstenglein** [aldabil21/react-scheduler#69]
In the US, daylight savings ended today. At 2am this morning, the clock rolled back an hour and we repeated the hour from 1am to 2am.

This leads to the following situation in the scheduler: there are two time slots labelled 1am and when I create an event after the time change, it is rendered an hour behind where it is supposed to be. I have attached a screenshot as an example. In the screenshot, I created an event on Friday from 9am to 10am. The label on the event is correct, but it is displayed in the scheduler in the 8am to 9am slot, which is incorrect.

<img width="1210" alt="Screen Shot 2022-11-06 at 5 55 13 PM" src="https://user-images.githubusercontent.com/22841845/200202550-51845150-1b43-4e75-9537-ac63f8ed288f.png">

**Comment by jackstenglein** [comment]
If I create an event on Sunday after the repeated hour, it displays correctly. All the other days display as in the screenshot though. Here is an updated screenshot showing this:

<img width="1292" alt="Screen Shot 2022-11-06 at 6 04 14 PM" src="https://user-images.githubusercontent.com/22841845/200202865-f1292145-c92c-4952-b584-e7563ffd1839.png">

**Comment by jackstenglein** [comment]
Apparently this is only an issue on the actual day that daylight savings ends. Today, I now see that the scheduler does not have the repeated hour, and events all show up in the correct time, except for Sunday, where they are an hour behind. Since the problem only exists for a single day, I'm not sure whether it is worth fixing this, but I'll leave this issue open for now.

<img width="1304" alt="Screen Shot 2022-11-07 at 8 54 10 AM" src="https://user-images.githubusercontent.com/22841845/200340758-579b0d7f-7bdc-4fa3-a981-9c2eb5a51316.png">

**Comment by aldabil21** [comment]
That might be a bug. I still want to look into #41 , it seems will be related
