### ISSUE TITLE
[Bug] Render happens twice every view load/change

### ISSUE THREAD

**Issue by npapapietro** [aldabil21/react-scheduler#71]
Every time the component is loaded, it rerenders itself an additional time when the view nav is changed from `Month`, `Day` or `Week`, but not when `Today` is clicked.

## Steps to duplicate

1. Fork repo 
2. Run `npm run start` 
3. Replace https://github.com/aldabil21/react-scheduler/blob/1a1275fc9a3a31e5d44c0a7c82803768fffc2c01/src/App.tsx#L11 with 

```typescript 
      getRemoteEvents={async () => {
         console.log("Getting Events at", new Date())
         return EVENTS;
      }}
```

![image](https://user-images.githubusercontent.com/16886148/201534768-d4d5809e-a5dc-4944-8fdd-5897ff49f9df.png)

I've tried running the profiler to see what is causing this, but no success. I can further see this happening if you insert a `console.log` into the `stateReducer` function here https://github.com/aldabil21/react-scheduler/blob/1a1275fc9a3a31e5d44c0a7c82803768fffc2c01/src/lib/context/state/stateReducer.ts#L8 you will see duplicate logs happening.

I haven't found a good work around as this calls external server duplicate times (which could be costly) when `getRemoteEvents` is passed as  prop.

**Comment by aldabil21** [comment]
Hi
Thx for the detailed issue. before I proceed with debugging, can you confirm if you are running the code with React __StrictMode__ or not? If yes, can you try again after removing the StrictMode line https://github.com/aldabil21/react-scheduler/blob/1a1275fc9a3a31e5d44c0a7c82803768fffc2c01/src/index.tsx#L7

**Comment by npapapietro** [comment]
Good catch, this bug is only present *with* StrictMode enabled.

**Comment by aldabil21** [comment]
This is not a bug. Its just __StrictMode__ work. Check: https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

> Strict mode can’t automatically detect side effects for you, but it can help you spot them by making them a little more deterministic. This is done by intentionally double-invoking the following functions: ...
