### ISSUE TITLE
Current time indicator is displaying above the modal

### ISSUE THREAD

**Issue by slcheungcasado** [aldabil21/react-scheduler#72]
There seems to be a visual bug with the time indicator div's z-index style value. 

![image](https://user-images.githubusercontent.com/23096257/201837156-49e3fdcc-578e-49ec-804b-3de94cb88f79.png)

The default value of 1500 makes it display above the modal.

![image](https://user-images.githubusercontent.com/23096257/201837102-fc0383f7-71f1-4581-9c5b-124c1364f1c5.png)

Editing this z-index value to <= 1300 seems to resolve this problem.

![image](https://user-images.githubusercontent.com/23096257/201840310-fe3f320b-c0c2-4bd8-9e56-bee239255f2d.png)

**Comment by aldabil21** [comment]
Thx for reporting. Fixed in v2.5.7
