### ISSUE TITLE
Custom Editor onConfirm and remote fetch

### ISSUE THREAD

**Issue by dtygel** [aldabil21/react-scheduler#76]
During some tests, it seems that when using custom editor, the "onConfirm" method in the main props of the Scheduler component isn't called, or am I wrong? There is an "onConfirm" method passed in the scheduler helper to the customEditor, but it looks like it doesn't call the onConfirm method of the props in the Scheduler component. Or I couldn't reproduce it.

**Comment by aldabil21** [comment]
You have 2 options here, either call the `onConfirm(event: ProcessedEvent, action: EventActions)` which is passed through the `SchedulerHelpers`. Or if you are using the `events` prop in a state where you render the `Scheduler` component, you can just update your own state and the calendar will be updated. Its your call.

If perhaps I didn't the issue you were describing, plz elaborate, or provide some code example.

**Comment by dtygel** [comment]
Thanks for the answer, @aldabil21 .

In fact, I was working first with the events prop. But maybe because of the quantity of events, when I change the events state, the event has still the same name, and is only changed after the view is changed. The new title is in the popup balloon already. It's very strange that the event is not rerendered after changing the states array. In this small clip, you can see it happening:

https://user-images.githubusercontent.com/3432789/203143402-de3cd891-6826-4edb-9f44-916322dcfcc6.mp4

**Comment by dtygel** [comment]
Never mind: I've forced a redraw including a loading overlay, and it now updated accordingly. Thanks!

**Comment by aldabil21** [comment]
Hmmm, this seems off, it should be updated accordingly. I wish you could share a minimal sandbox that I can debug.

**Comment by dtygel** [comment]
ok, sure. I'll create a branch for you in our project.
