### ISSUE TITLE
Events spanning multiple days do not render correctly

### ISSUE THREAD

**Issue by jackstenglein** [aldabil21/react-scheduler#78]
For example, create a single event that starts on 11/23 at 11pm and ends at 11/24 at 4am. The event will show on 11/23 and extend to the bottom of the calendar, but will not show on 11/24.

I have a codesandbox here, but you may need to edit the times in order to have it work for your timezone:
https://codesandbox.io/s/test-events-across-2-days-4o6gb4?file=/src/App.js

**Comment by aldabil21** [comment]
I think I missed this part in the [`differenceInDays`](https://date-fns.org/v2.29.3/docs/differenceInDays) doc, difference in days only if it's more tha 24h, which is not the case in your sandbox.

Check upgrade to v2.5.8, this sandbox similar to your example: https://codesandbox.io/s/test-events-across-2-days-forked-v8kxkq?file=/src/App.js
