### ISSUE TITLE
Dynamic resources break upon state change

### ISSUE THREAD

**Issue by dtygel** [aldabil21/react-scheduler#90]
Hi!

I identified a bug, which I was able to reproduce in the following sandbox:

https://codesandbox.io/s/resources-forked-0n0f32?file=/src/App.tsx

To reproduce the bug, just go to the 3rd or 4th tab, and then change the resources to "Alternative resources", which has only 2 items, and the calendar breaks. The ideal behaviour would be to reset to first tab whenever the resources change.

I'd be glad to send a PR, but I'm quite at lost on how to correlate the state of the active tab and the state changes of the resources.

**Comment by aldabil21** [comment]
Thank you for reporting, Try the release after #91 and feel free to re-open if it still has an issue
