### ISSUE TITLE
readOnly on calendar itself

### ISSUE THREAD

**Issue by JeanPaulMolfino** [aldabil21/react-scheduler#95]
Hi! 

I was wondering if there is any actual property to make the calendar to show info only and not being able to add new events... Not even the popup asking for data for the new entry.

Thanks for your attention.

**Comment by aldabil21** [comment]
Hi

1. you would use the `cellRenderer` on each view to override the default `cell` behaviour. example: https://codesandbox.io/s/custom-cell-action-n02dv
2. Use `editable`/`deletable` to control the behaviour calendar-wise/event-wise.
